import { Kysely, PostgresDialect, type LogEvent } from 'kysely';
import pg from 'pg';
import type { DB } from './db-types.ts';

// How a process opens its database (ADR-0012), shared by the web app (apps/web/src/server/db/database.ts) and the
// worker (apps/worker/src/db/database.ts). Each process calls this once, with its own role's connection string, pool
// size and application_name; timeouts are set on the role (db/bootstrap/10-roles.sql), never here. Types come from
// the migrated schema (db-types.ts, generated by `pnpm db:migrate`).

/**
 * bigint (int8) arrives from node-postgres as a string, because it can exceed JavaScript's safe integers. Our
 * bigints are ids, counts and amounts far below 2^53 (an amount's CHECK keeps it under 10^15 tomans, ADR-0014), so
 * they become numbers, and a value that does not fit throws instead of silently losing precision. numeric stays a
 * string and is converted on purpose where it is used.
 */
export function parseInt8(text: string): number {
  const value = Number(text);
  if (!Number.isSafeInteger(value)) {
    throw new RangeError(`int8 value ${text} is outside JavaScript's safe integer range`);
  }
  return value;
}

const typeParsers: pg.CustomTypesConfig = {
  getTypeParser: (id, format) =>
    id === pg.types.builtins.INT8 ? parseInt8 : (pg.types.getTypeParser(id, format) as unknown),
};

export type DatabaseOptions = {
  /** The connection string of the process's own role. */
  connectionString: string;
  /** Names the process in pg_stat_activity and the server log: `carshenas-web`, `carshenas-worker`. */
  applicationName: string;
  /**
   * Connections in the pool. A small VPS saturates at two to four busy connections per core; beyond that queries only
   * queue inside PostgreSQL. Measure pool waits (pool.waitingCount) before raising it: a starved pool usually means
   * slow queries.
   */
  max: number;
  idleTimeoutMillis?: number;
  connectionTimeoutMillis?: number;
  /** Every statement passes through here (query-log.ts). */
  log?: (event: LogEvent) => void;
  /** An idle client lost its connection (a database restart). Unhandled, that error would crash the process. */
  onIdleError: (error: Error) => void;
};

/** One pool and its Kysely instance; `destroy()` on the instance ends the pool. */
export function createDatabase(options: DatabaseOptions): Kysely<DB> {
  const pool = new pg.Pool({
    connectionString: options.connectionString,
    max: options.max,
    idleTimeoutMillis: options.idleTimeoutMillis ?? 30_000,
    connectionTimeoutMillis: options.connectionTimeoutMillis ?? 5_000,
    application_name: options.applicationName,
    types: typeParsers,
  });
  pool.on('error', options.onIdleError);
  return new Kysely<DB>({ dialect: new PostgresDialect({ pool }), log: options.log });
}
