/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface CrawlFeed {
  /**
   * Names the feed within its source, for example tracked_models.
   */
  feed_key: string;
  /**
   * The newest sort time, by the source's own clock, down from which a finished round read the whole feed; null before the first round finishes. Rows sorted after it are new or were moved up since.
   */
  read_through_at: Timestamp | null;
  /**
   * When the latest round started; a new round starts only ten minutes or more after it.
   */
  round_started_at: Timestamp | null;
  source_id: string;
}

export interface CrawlLane {
  cooldown_reason: "unavailable" | "rate_limited" | null;
  /**
   * The lane sends nothing until then: after three transient failures in a row (unavailable), or after a 429 (rate_limited). The next request after it is the probe.
   */
  cooldown_until: Timestamp | null;
  /**
   * Cool-downs in a row without a successful request between them; each one lasts about twice the previous, up to an hour.
   */
  cooldowns: Generated<number>;
  /**
   * Timeouts, server errors and dropped connections in a row; three open the breaker (a cool-down). Any other answer resets it.
   */
  failure_streak: Generated<number>;
  /**
   * When the latest request started.
   */
  last_request_at: Timestamp | null;
  /**
   * Who holds the request in flight (worker process and job), or null. A lease that outlives lease_until is free again, so a crashed worker cannot hold the lane.
   */
  lease_holder: string | null;
  lease_until: Timestamp | null;
  /**
   * The earliest start of the next request (from the lane's creation at first): the end of the previous one plus its gap (five times its duration, at least source.min_request_interval_ms, doubled for 24 hours after a 429, at most 30 s unless the interval is longer).
   */
  next_request_at: Generated<Timestamp>;
  /**
   * The latest 429. For 24 hours after it the gap is doubled, and another 429 stops the source (ADR-0018 point 6).
   */
  rate_limited_at: Timestamp | null;
  source_id: string;
}

export interface CrawlRun {
  /**
   * What the run did, written once when it closes: rows read, new listings, snapshots stored or unchanged, price events, and so on, by kind. Its requests and their outcomes are in fetch_log.
   */
  counts: Generated<Json>;
  finished_at: Timestamp | null;
  id: ColumnType<number, never, never>;
  /**
   * What the run spent its request on (ADR-0017 point 5): discovery (a page of the newest listings of tracked models), detail (one listing's page), measure (a page of a measurement walk).
   */
  kind: "discovery" | "detail" | "measure";
  policy_check_id: number;
  source_id: string;
  started_at: Generated<Timestamp>;
  /**
   * running until its job ends; succeeded or failed then; stopped_on_block when its request was refused (a 401 or 403, a challenge page or empty answer, or a second 429 within 24 hours) and the source stopped with it (ADR-0008 point 6, ADR-0018).
   */
  status: Generated<"running" | "succeeded" | "failed" | "stopped_on_block">;
}

export interface FetchLog {
  crawl_run_id: number;
  duration_ms: number | null;
  /**
   * The response ETag, sent back as If-None-Match on the next visit (ADR-0008 point 5).
   */
  etag: string | null;
  http_status: number | null;
  id: ColumnType<number, never, never>;
  /**
   * The response Last-Modified, sent back as If-Modified-Since on the next visit.
   */
  last_modified: string | null;
  listing_id: number | null;
  /**
   * How the request reached the source: http_get or http_post to its pages or public web API (a crawl), official_api through a partner API it grants.
   */
  method: Generated<"http_get" | "http_post" | "official_api">;
  /**
   * blocked, rate_limited and challenge stop the source (ADR-0008 point 6); error means no usable response (network failure, timeout).
   */
  outcome: "ok" | "not_modified" | "not_found" | "gone" | "blocked" | "rate_limited" | "challenge" | "error";
  requested_at: Generated<Timestamp>;
  snapshot_id: number | null;
  source_id: string;
  url: string;
}

export interface Listing {
  created_at: Generated<Timestamp>;
  /**
   * When the ad left the market; set exactly when the status is off the market.
   */
  delisted_at: Timestamp | null;
  id: ColumnType<number, never, never>;
  /**
   * The latest fetch that showed the ad, to within a day: the crawler refreshes it when it is more than a day old (fetch_log keeps every visit). Deliberately not indexed, so those updates stay HOT.
   */
  last_seen_at: Timestamp | null;
  /**
   * When the ad went on the market: the source's posting time when the page shows it, else our first sighting. Native drafts, later, have none: the native-listings migration relaxes NOT NULL for them.
   */
  listed_at: Timestamp;
  /**
   * external: crawled or read through an official API; native: created on Carshenas (later).
   */
  origin: Generated<"external" | "native">;
  source_id: string;
  /**
   * The source's own id or token for the ad; with source_id it is the natural key the crawler upserts on.
   */
  source_listing_key: string | null;
  /**
   * active: on the market; sold, expired, gone (disappeared from the source): off the market; removed: taken down by Carshenas. Changes follow listing_status_transition.
   */
  status: "active" | "sold" | "expired" | "gone" | "removed";
  /**
   * Where the ad lives on its source; the click-out target.
   */
  url: string | null;
}

export interface ListingPriceEvent {
  /**
   * The asking price in whole tomans, exactly when price_type is asking.
   */
  asking_price_toman: number | null;
  id: ColumnType<number, never, never>;
  /**
   * The latest earlier asking price, filled by the trigger, across negotiable and placeholder events: an asking price below it is a drop.
   */
  last_asking_price_toman: ColumnType<number | null, never, never>;
  listing_id: number;
  /**
   * When the source showed this price: the start of the request whose snapshot is the evidence. Events of a listing are inserted in this order.
   */
  observed_at: Timestamp;
  /**
   * The previous event's asking price, filled by the trigger; null when that event carried none.
   */
  previous_price_toman: ColumnType<number | null, never, never>;
  /**
   * The type of the listing's previous event, filled by the trigger; null for its first.
   */
  previous_price_type: ColumnType<"asking" | "negotiable" | "installment" | "placeholder" | null, never, never>;
  /**
   * asking (an amount), negotiable («توافقی»), installment (an installment offer: its figure is not the car's price), placeholder (a token figure such as 1,000 tomans); only asking carries an amount.
   */
  price_type: "asking" | "negotiable" | "installment" | "placeholder";
  /**
   * When we stored the event; differs from observed_at when history is re-derived.
   */
  recorded_at: Generated<Timestamp>;
  /**
   * The snapshot the price was read from: the evidence.
   */
  snapshot_id: number;
}

export interface ListingStatusTransition {
  from_status: string;
  origin: "external" | "native";
  to_status: string;
}

export interface ModelVolume {
  /**
   * Listings the walk read in the slice, promoted rows counted once.
   */
  active_count: number;
  /**
   * Whether the walk reached the end of the slice; false when the source stopped answering pages first or the walk hit its page limit, and then active_count is a lower bound.
   */
  complete: boolean;
  id: ColumnType<number, never, never>;
  /**
   * all (every car), brand, model or trim: how finely the slice is cut.
   */
  level: "all" | "brand" | "model" | "trim";
  /**
   * List pages the walk read: how deep the source let it follow the slice.
   */
  pages_read: number;
  source_id: string;
  /**
   * The source's own filter value for the slice, as its search takes it (Divar's brand_model: ROOT, Peugeot, Peugeot 206, Peugeot 206 5); mapped to the catalogue when CS-50 knows it.
   */
  source_model_key: string;
  /**
   * When the sweep (or measurement) that counted it started: it groups one sweep's slices.
   */
  swept_at: Timestamp;
}

export interface SchemaMigrations {
  version: string;
}

export interface Snapshot {
  /**
   * Version of the crawler's canonical form. A new version may re-express an unchanged page as new JSON, which is then a new snapshot; identical JSON is one snapshot whatever the version.
   */
  canonical_version: number;
  /**
   * Computed by the database from payload, so the deduplication key can never disagree with the content.
   */
  content_sha256: ColumnType<Buffer, never, never>;
  /**
   * When this content was first fetched; later identical fetches point here from fetch_log.
   */
  first_fetched_at: Timestamp;
  id: ColumnType<number, never, never>;
  listing_id: number;
  /**
   * What the page showed, as canonical JSON: phone numbers and other personal data are removed before storage (ADR-0008 point 7). Compressed with lz4 through default_toast_compression (db/postgresql.conf).
   */
  payload: Json;
  url: string;
}

export interface Source {
  /**
   * crawl: our crawler reads the source's pages or public web API within ADR-0008 (Divar through its web API, by the owner's decision of 2026-09-27); official_api: single items through a partner API the source grants; native: our own database.
   */
  access_method: "crawl" | "official_api" | "native";
  base_url: string;
  /**
   * enabled or paused by a human; stopped_on_block by the crawler on a 403, 429 or challenge (ADR-0008 point 6), until a human reads the evidence and re-enables it.
   */
  crawl_state: Generated<"enabled" | "paused" | "stopped_on_block">;
  created_at: Generated<Timestamp>;
  /**
   * Stable code used in URLs, logs and job names, for example bama.
   */
  id: string;
  /**
   * public: its listings appear in search; requester_only: a source whose rules allow reading a pasted link but not publishing it, shown only to the buyer who pasted it (CS-19).
   */
  listing_visibility: "public" | "requester_only";
  /**
   * Milliseconds between two requests to this source; at least 3000 for crawled sources (ADR-0008 point 5). robots.txt is recorded, not followed, so a Crawl-delay does not lengthen it; the lane waits longer after a slow answer and after a 429 (ADR-0018).
   */
  min_request_interval_ms: number | null;
  name_fa: string;
  /**
   * external: listings on other sites; native: listings created on Carshenas; benchmark: published price tables, never listings.
   */
  origin: "external" | "native" | "benchmark";
  /**
   * How many days old the latest policy check may be before a crawl is refused.
   */
  policy_max_age_days: Generated<number>;
  stop_reason: "blocked" | "rate_limited" | "challenge" | null;
  /**
   * When the crawler stopped the source: the requested_at of the blocked request in fetch_log, which is the evidence.
   */
  stopped_at: Timestamp | null;
}

export interface SourceCurrentPolicy {
  checked_at: Timestamp | null;
  checked_by: string | null;
  conditions: string | null;
  id: number | null;
  photos_allowed: boolean | null;
  source_id: string | null;
  verdict: string | null;
}

export interface SourcePolicyCheck {
  checked_at: Timestamp;
  checked_by: string;
  conditions: string | null;
  id: ColumnType<number, never, never>;
  /**
   * Whether this source's rules allow downloading and re-hosting its photos (ADR-0010).
   */
  photos_allowed: boolean;
  /**
   * The robots.txt text as read, kept as evidence.
   */
  robots_txt: string | null;
  source_id: string;
  terms_summary: string;
  terms_url: string | null;
  verdict: "allowed" | "allowed_with_conditions" | "not_allowed";
}

export interface DB {
  crawl_feed: CrawlFeed;
  crawl_lane: CrawlLane;
  crawl_run: CrawlRun;
  fetch_log: FetchLog;
  listing: Listing;
  listing_price_event: ListingPriceEvent;
  listing_status_transition: ListingStatusTransition;
  model_volume: ModelVolume;
  schema_migrations: SchemaMigrations;
  snapshot: Snapshot;
  source: Source;
  source_current_policy: SourceCurrentPolicy;
  source_policy_check: SourcePolicyCheck;
}
