/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type DealRating = "fair" | "good" | "great" | "high" | "overpriced";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  created_at: Generated<Timestamp>;
  id: ColumnType<number, never, never>;
  /**
   * Argon2id as a PHC string (ADR-0020 point 4). Never the password itself; the read-only role cannot read it.
   */
  password_hash: string;
  /**
   * buyer by default; superadmin only through pnpm account:superadmin, recorded in account_role_change. The web role reads it and can never write it.
   */
  role: Generated<"buyer" | "superadmin">;
  /**
   * Lowercase Latin letters, digits and underscore, 3 to 30 characters, starting with a letter; normalised before it is stored (capitals lowered, Persian digits made Latin). Never logged: people type passwords into it by mistake.
   */
  username: string;
}

export interface AccountRoleChange {
  account_id: number;
  changed_at: Generated<Timestamp>;
  /**
   * Who ran the command: the operating-system user and host, for example cli:pedram@carshenas-1.
   */
  changed_by: string;
  /**
   * NULL when the account was created with to_role.
   */
  from_role: "buyer" | "superadmin" | null;
  id: ColumnType<number, never, never>;
  to_role: "buyer" | "superadmin";
}

export interface AccountSession {
  account_id: number;
  created_at: Generated<Timestamp>;
  /**
   * Fixed at sign-in: 30 days for a buyer, 12 hours for the superadmin. Never extended; sign-out deletes the row.
   */
  expires_at: Timestamp;
  id: ColumnType<number, never, never>;
  token_sha256: Buffer;
}

export interface AiAnswer {
  /**
   * The model id the provider reported: Metis may route a requested id to another model (CS-42).
   */
  answering_model: string;
  /**
   * SHA-256 of the task, the prompt version, the requested model with its options and the rendered input (cacheKey in packages/ai/src/answer-cache.ts). The input itself is never stored.
   */
  cache_key: Buffer;
  /**
   * What producing the answer cost at the live Metis list price, every attempt included, in millionths of a US dollar; NULL when the model had no price.
   */
  cost_usd_micros: number | null;
  created_at: Generated<Timestamp>;
  id: ColumnType<number, never, never>;
  /**
   * The model id the layer asked for, as the route takes it (claude-haiku-4-5).
   */
  model: string;
  /**
   * The answer as the task schema and checks accepted it. Built from text that was redacted before it was sent (ADR-0019), so it holds no seller contact details.
   */
  output: Json;
  /**
   * The first 16 hex digits of the SHA-256 of the instructions, the output schema, the version of the task checks and the output budget.
   */
  prompt_version: string;
  /**
   * The Metis native route the model was asked on (ADR-0019 point 2).
   */
  provider: "openai" | "anthropic" | "google" | "deepseek";
  /**
   * The registry name of the AI task: <area>.<what>, such as listing.facts.
   */
  task: string;
}

export interface AiEvaluation {
  created_at: Generated<Timestamp>;
  evaluated_on: Timestamp;
  fields_right: number;
  /**
   * Fields scored over those items; an item without a valid answer counts wrong on every field.
   */
  fields_scored: number;
  id: ColumnType<number, never, never>;
  /**
   * Of injected_items, those the step held for a person instead of using.
   */
  injected_held: number;
  /**
   * Items of the whole labelled set whose text addresses the model (prompt injection); 0 when the set has none.
   */
  injected_items: number;
  /**
   * Labelled items scored for items_right and the fields: the test split, held out while the prompt was written.
   */
  items: number;
  /**
   * Items whose every scored field was right.
   */
  items_right: number;
  model: string;
  prompt_version: string;
  /**
   * The report the scores come from, relative to the repository root.
   */
  report_path: string;
  /**
   * The AI layer's task name, as in model_spend (listing.facts).
   */
  task: string;
}

export interface AuthThrottle {
  /**
   * Consecutive failed sign-ins for sign_in_account and sign_in_device; failed sign-ins, sign-up attempts, username checks or questions put to the language model (understand_address) within the window for the address scopes.
   */
  hits: Generated<number>;
  id: ColumnType<number, never, never>;
  /**
   * For sign_in_account and sign_in_device, the earliest time the next attempt may start: a growing wait after repeated failures, or a 15-second lease while one attempt is being checked. The address scopes leave it at its default; their wait ends an hour after window_started_at.
   */
  next_attempt_at: Generated<Timestamp>;
  scope: "sign_in_account" | "sign_in_device" | "sign_in_address" | "sign_up_address" | "username_check_address" | "understand_address";
  /**
   * HMAC-SHA-256, under CARSHENAS_AUTH_KEY, of the typed username (whether or not the account exists), a device token or the client address.
   */
  subject_hmac: Buffer;
  /**
   * When the counted streak or window began.
   */
  window_started_at: Generated<Timestamp>;
}

export interface BodyType {
  code: string;
  label_fa: string;
  position: number;
}

export interface CatalogueAlias {
  alias: string;
  /**
   * fa_normalize(alias): what matching compares.
   */
  alias_norm: ColumnType<string, never, never>;
  created_at: Generated<Timestamp>;
  id: ColumnType<number, never, never>;
  make_id: number | null;
  model_id: number | null;
  script: "fa" | "latin" | "spelled";
  source_id: string | null;
  status: "curated" | "suggested" | "rejected";
  trim_id: number | null;
}

export interface CatalogueSourceKey {
  created_at: Generated<Timestamp>;
  level: "make" | "model" | "trim";
  make_id: number;
  model_id: number | null;
  source_id: string;
  source_model_key: string;
  trim_id: number | null;
}

export interface City {
  id: ColumnType<number, never, never>;
  name_fa: string;
  slug: string;
}

export interface Colour {
  code: string;
  family: "white" | "black" | "grey" | "silver" | "blue" | "red" | "green" | "yellow" | "orange" | "brown" | "beige" | "gold" | "purple" | "pink" | "other";
  label_fa: string;
}

export interface CrawlFeed {
  /**
   * Names the feed within its source, for example tracked_models.
   */
  feed_key: string;
  /**
   * The newest sort time, by the source's own clock, down from which a finished round read the whole feed; null before the first round finishes. Rows sorted after it are new or were moved up since.
   */
  read_through_at: Timestamp | null;
  /**
   * When the latest round started; a new round starts only ten minutes or more after it.
   */
  round_started_at: Timestamp | null;
  source_id: string;
}

export interface CrawlLane {
  /**
   * The Tehran day (Asia/Tehran) whose requests budget_spent counts; the first lease of a new day starts the count again. NULL before the lane's first request.
   */
  budget_day: Timestamp | null;
  /**
   * Requests leased on budget_day, counted when the lease is taken, so a request is paid for even if its answer never arrives; compared with source.daily_request_budget less the reserve of the job's priority (ADR-0017 point 5).
   */
  budget_spent: Generated<number>;
  cooldown_reason: "unavailable" | "rate_limited" | null;
  /**
   * The lane sends nothing until then: after three transient failures in a row (unavailable), or after a 429 (rate_limited). The next request after it is the probe.
   */
  cooldown_until: Timestamp | null;
  /**
   * Cool-downs in a row without a successful request between them; each one lasts about twice the previous, up to an hour.
   */
  cooldowns: Generated<number>;
  /**
   * Timeouts, server errors and dropped connections in a row; three open the breaker (a cool-down). Any other answer resets it.
   */
  failure_streak: Generated<number>;
  /**
   * When the latest request started.
   */
  last_request_at: Timestamp | null;
  /**
   * Who holds the request in flight (worker process and job), or null. A lease that outlives lease_until is free again, so a crashed worker cannot hold the lane.
   */
  lease_holder: string | null;
  lease_until: Timestamp | null;
  /**
   * The earliest start of the next request (from the lane's creation at first): the end of the previous one plus its gap (five times its duration, at least source.min_request_interval_ms, doubled for 24 hours after a 429, at most 30 s unless the interval is longer).
   */
  next_request_at: Generated<Timestamp>;
  /**
   * The latest 429. For 24 hours after it the gap is doubled, and another 429 stops the source (ADR-0018 point 6).
   */
  rate_limited_at: Timestamp | null;
  source_id: string;
}

export interface CrawlRequest {
  created_at: Generated<Timestamp>;
  /**
   * When the last decision took effect (clock_timestamp()).
   */
  decided_at: Timestamp | null;
  /**
   * The superadmin who last decided: decide_crawl_request() refuses any other account. Earlier decisions are in crawl_request_decision.
   */
  decided_by_account_id: number | null;
  /**
   * Why the request was declined, in the superadmin's words, shown to the buyers who asked: 1 to 300 characters of plain text.
   */
  decline_reason: string | null;
  fulfilled_at: Timestamp | null;
  id: ColumnType<number, never, never>;
  model_id: number;
  state: Generated<"pending" | "approved" | "declined" | "fulfilled">;
  /**
   * NULL asks for the whole model; a trim asks for that trim only.
   */
  trim_id: number | null;
}

export interface CrawlRequestDecision {
  crawl_request_id: number;
  decided_at: Generated<Timestamp>;
  decided_by_account_id: number;
  decision: "approved" | "declined";
  from_state: "pending" | "approved" | "declined";
  id: ColumnType<number, never, never>;
  reason: string | null;
}

export interface CrawlRequestFile {
  crawl_request_id: number;
  created_at: Generated<Timestamp>;
  search_file_id: number;
}

export interface CrawlRun {
  /**
   * What the run did, written once when it closes: rows read, new listings, snapshots stored or unchanged, price events, and so on, by kind. Its requests and their outcomes are in fetch_log.
   */
  counts: Generated<Json>;
  finished_at: Timestamp | null;
  id: ColumnType<number, never, never>;
  /**
   * What the run spent its request on (ADR-0017 point 5): discovery (a page of the newest listings of tracked models), detail (a new or changed listing's page), measure (a page of a measurement walk), sweep (a list page of the inventory sweep), check (a listing's page read to confirm it left the market), recheck (a listing's page a buyer asked to re-read).
   */
  kind: "discovery" | "detail" | "measure" | "sweep" | "check" | "recheck";
  policy_check_id: number;
  source_id: string;
  started_at: Generated<Timestamp>;
  /**
   * running until its job ends; succeeded or failed then; stopped_on_block when its request was refused (a 401 or 403, a challenge page or empty answer, or a second 429 within 24 hours) and the source stopped with it (ADR-0008 point 6, ADR-0018).
   */
  status: Generated<"running" | "succeeded" | "failed" | "stopped_on_block">;
}

export interface Extraction {
  ai_answer_id: number;
  created_at: Generated<Timestamp>;
  hold_reasons: string[];
  id: ColumnType<number, never, never>;
  /**
   * The snapshot's listing, part of the composite key to snapshot so an extraction cannot name another listing's snapshot.
   */
  listing_id: number;
  snapshot_id: number;
  /**
   * usable: its accepted fields may be used; held: a person reads it first, because the listing addressed the model or hid tag characters (hold_reasons).
   */
  status: "usable" | "held";
}

export interface ExtractionField {
  confidence: Numeric;
  evidence: string;
  extraction_id: number;
  field: string;
  status: "accepted" | "needs_review";
  /**
   * extraction_field_def.min_confidence when the field was stored, kept for audit.
   */
  threshold: Numeric;
  /**
   * The schema's value code, such as partial, down_payment, free_zone or 5_or_more; not_stated when the text says nothing.
   */
  value: string;
}

export interface ExtractionFieldDef {
  code: string;
  min_confidence: Numeric;
}

export interface FetchLog {
  crawl_run_id: number;
  duration_ms: number | null;
  /**
   * The response ETag, sent back as If-None-Match on the next visit (ADR-0008 point 5).
   */
  etag: string | null;
  http_status: number | null;
  id: ColumnType<number, never, never>;
  /**
   * The response Last-Modified, sent back as If-Modified-Since on the next visit.
   */
  last_modified: string | null;
  listing_id: number | null;
  /**
   * How the request reached the source: http_get or http_post to its pages or public web API (a crawl), official_api through a partner API it grants.
   */
  method: Generated<"http_get" | "http_post" | "official_api">;
  /**
   * What came back. blocked (401, 403) and challenge stop the source, and so does a second rate_limited (429) within 24 hours (ADR-0008 point 6, ADR-0018); error means no usable answer: a network failure, a timeout, a 5xx, or an answer the crawler could not read.
   */
  outcome: "ok" | "not_modified" | "not_found" | "gone" | "blocked" | "rate_limited" | "challenge" | "error";
  requested_at: Generated<Timestamp>;
  snapshot_id: number | null;
  source_id: string;
  url: string;
}

export interface FreshnessMeasurement {
  active_listings: number;
  id: ColumnType<number, never, never>;
  /**
   * Median minutes since each active listing was last seen or checked, at measured_at. The target is under 24 hours.
   */
  last_seen_age_p50_minutes: number | null;
  last_seen_age_p90_minutes: number | null;
  /**
   * Listings whose delisted_at falls in the 24 hours before measured_at: sold, expired or gone.
   */
  left_market: number;
  measured_at: Timestamp;
  /**
   * Listings first stored in the 24 hours before measured_at.
   */
  new_listings: number;
  /**
   * Median minutes from posting (listed_at) to first storing (created_at), over the listings first stored in the 24 hours whose page has been read, so their posting time is the source's own. The target is under an hour for tracked models.
   */
  posting_to_first_seen_p50_minutes: number | null;
  posting_to_first_seen_p90_minutes: number | null;
  /**
   * Active listings seen in a list or checked on their own page within 48 hours: what a results page may show (ADR-0017 point 6).
   */
  seen_within_48h: number;
  source_id: string;
  /**
   * The tracked model's own filter value on the source (Divar's brand_model); its trims are counted with it. NULL: the whole source.
   */
  source_model_key: string | null;
}

export interface JobStateChange {
  action: "retry" | "cancel";
  /**
   * When the change took effect, holding the job's lock (clock_timestamp()).
   */
  changed_at: Generated<Timestamp>;
  /**
   * The superadmin who made the change; change_job_state() refuses any other account.
   */
  changed_by_account_id: number;
  /**
   * pgboss.job.state before the change.
   */
  from_state: string;
  id: ColumnType<number, never, never>;
  /**
   * pgboss.job.id; the job itself may since have been deleted by pg-boss.
   */
  job_id: string;
  /**
   * The pg-boss queue of the job (pgboss.job.name).
   */
  queue: string;
}

export interface Listing {
  /**
   * True when the listing says the car can be bought in installments («امکان خرید قسطی»); null when it says nothing. Its price may still be the full price.
   */
  accepts_installments: boolean | null;
  /**
   * True when the listing says the seller takes a car in exchange («مایل به معاوضه»); null when it says nothing.
   */
  accepts_swap: boolean | null;
  /**
   * The asking price in whole tomans, exactly when price_type is asking.
   */
  asking_price_toman: number | null;
  /**
   * The seller's own rating of the body, a claim rather than an inspection: intact, minor_scratches, paintless_dent_repair, partly_repainted, repainted_around («دوررنگ»), fully_repainted, accident_damaged or salvage.
   */
  body_condition: "intact" | "minor_scratches" | "paintless_dent_repair" | "partly_repainted" | "repainted_around" | "fully_repainted" | "accident_damaged" | "salvage" | null;
  /**
   * What the catalogue knows of the car (CS-50): trim (make, model and trim), model (the source named the model only: trim unknown) or unmatched (its source_model_key is not in the catalogue). NULL until matched. Never a guess.
   */
  catalogue_match: "trim" | "model" | "unmatched" | null;
  /**
   * The city the post is in (Divar: city.second_slug).
   */
  city_id: number | null;
  /**
   * The colour the post states, as a colour code (CS-50); an unknown word is kept in listing_unparsed_value.
   */
  colour: string | null;
  created_at: Generated<Timestamp>;
  /**
   * When the listing left the market; set exactly when the status is off the market.
   */
  delisted_at: Timestamp | null;
  /**
   * The district the post names, as written (Divar: seo.web_info.district_persian).
   */
  district_fa: string | null;
  /**
   * The down payment an installment listing shows as its price, in whole tomans, exactly when price_type is installment.
   */
  down_payment_toman: number | null;
  /**
   * The seller's own rating of the engine: sound, needs_repair, replaced or repaired.
   */
  engine_condition: "sound" | "needs_repair" | "replaced" | "repaired" | null;
  /**
   * The engine volume in cubic centimetres that the listing's title states (500 to 9000), read by the parser; null when it states none. Beats the volume of the listing's trim and model (model_spec).
   */
  engine_volume_cc: number | null;
  /**
   * The source's own end date for this listing (Divar: seo.unavailable_after, Tehran time), read from its page; past it the listing is marked expired without a request (ADR-0017 point 3). NULL when the source gives none or the page was never read.
   */
  expires_at: Timestamp | null;
  /**
   * The seller's own rating of the front chassis: intact (sound and sealed), repainted or damaged.
   */
  front_chassis_condition: "intact" | "repainted" | "damaged" | null;
  /**
   * petrol, dual_fuel_factory (petrol and CNG, fitted by the maker), dual_fuel_aftermarket (CNG fitted later), hybrid, plug_in_hybrid, electric or diesel.
   */
  fuel: "petrol" | "dual_fuel_factory" | "dual_fuel_aftermarket" | "hybrid" | "plug_in_hybrid" | "electric" | "diesel" | null;
  /**
   * manual or automatic.
   */
  gearbox: "manual" | "automatic" | null;
  /**
   * The seller's own rating of the gearbox: sound, needs_repair, replaced or repaired.
   */
  gearbox_condition: "sound" | "needs_repair" | "replaced" | "repaired" | null;
  id: ColumnType<number, never, never>;
  /**
   * Months of third-party insurance left, as the listing stated them.
   */
  insurance_months_left: number | null;
  /**
   * When the listing's own page was last read (a detail, check or recheck run), as against last_seen_at, its latest sighting in a list. A buyer's re-check is skipped while this is younger than the freshness window (six hours, ADR-0017 point 3).
   */
  last_checked_at: Timestamp | null;
  /**
   * The latest fetch that showed the listing, to within a day: the crawler refreshes it when it is more than a day old (fetch_log keeps every visit). Deliberately not indexed, so those updates stay HOT.
   */
  last_seen_at: Timestamp | null;
  /**
   * When the listing went on the market: the source's posting time when the page shows it, else our first sighting. Native drafts, later, have none: the native-listings migration relaxes NOT NULL for them.
   */
  listed_at: Timestamp;
  make_id: number | null;
  /**
   * Kilometres driven, as stated, from 0 (a new car) to 9,999,999. Null when the listing stated none, stated Divar's 1,000,000, which stands for unknown, or stated more than any car drives (kept as unparsed).
   */
  mileage_km: number | null;
  model_id: number | null;
  /**
   * The Gregorian model year, only when the listing stated it.
   */
  model_year_ad: number | null;
  /**
   * The Solar Hijri model year, set whenever a year is known: as stated, or model_year_ad - 621 when only a Gregorian year was stated. Search, comparables and valuation read this column.
   */
  model_year_sh: number | null;
  /**
   * The calendars the listing stated its model year in: sh (Solar Hijri only), ad (Gregorian only) or both (ADR-0014); null when it stated no single year.
   */
  model_year_written: "sh" | "ad" | "both" | null;
  /**
   * external: crawled or read through an official API; native: created on Carshenas (later).
   */
  origin: Generated<"external" | "native">;
  /**
   * The version of its source's parser that last derived the columns above from the listing's latest snapshot (CS-34); null until derived.
   */
  parser_version: number | null;
  /**
   * What the listing asks (ADR-0014): asking (an amount), negotiable («توافقی»), installment (its figure is a down payment, read from the text by CS-52), placeholder (a token figure such as 1,000 tomans, kept only in the snapshot); null until read.
   */
  price_type: "asking" | "negotiable" | "installment" | "placeholder" | null;
  /**
   * The seller's own rating of the rear chassis: intact (sound and sealed), repainted or damaged.
   */
  rear_chassis_condition: "intact" | "repainted" | "damaged" | null;
  /**
   * dealer («نمایشگاه») or private, as the source marks the seller.
   */
  seller_type: "dealer" | "private" | null;
  source_id: string;
  /**
   * The source's own id or token for the listing; with source_id it is the natural key the crawler upserts on.
   */
  source_listing_key: string | null;
  /**
   * The source's own make, model and trim value (Divar's brand_model, such as «Peugeot 206 5»), as model_volume keys it; the catalogue (CS-50) maps it to a trim.
   */
  source_model_key: string | null;
  /**
   * active: on the market; sold, expired, gone (disappeared from the source): off the market; removed: taken down by Carshenas. Changes follow listing_status_transition.
   */
  status: "active" | "sold" | "expired" | "gone" | "removed";
  /**
   * The listing's title as its source shows it, with phone numbers removed as in its snapshot.
   */
  title: string | null;
  trim_id: number | null;
  /**
   * Where the listing lives on its source; the click-out target.
   */
  url: string | null;
}

export interface ListingFactEvidence {
  /**
   * The phrase of the listing the model copied, at most 200 characters; null when it was longer or looks like a way to reach the seller.
   */
  evidence: string | null;
  field: string | null;
  listing_id: number | null;
  /**
   * The fact's value code (partial, down_payment, free_zone, 5_or_more...), never not_stated.
   */
  value: string | null;
}

export interface ListingFilterRow {
  /**
   * had_accident when the text states one or the body is rated accident-damaged or salvage; none when the text says so; else null.
   */
  accident: string | null;
  asking_price_toman: number | null;
  body_condition: string | null;
  /**
   * The trim's body type where it differs from its model's, else the model's (CS-50).
   */
  body_type: string | null;
  car_origin: string | null;
  /**
   * damaged when either chassis is rated damaged or the text says so; repainted when either is repainted; intact when both are rated intact, or the text says so and the seller rated neither; else null.
   */
  chassis_condition: string | null;
  city_id: number | null;
  /**
   * The city's slug (tehran).
   */
  city_key: string | null;
  /**
   * The family the listing's colour groups in (colour.family).
   */
  colour_family: string | null;
  /**
   * The rating of the latest succeeded valuation run (CS-51); null when unrated or not valued.
   */
  deal_rating: DealRating | null;
  district_fa: string | null;
  /**
   * city slug.district as the listing names it (tehran.ونک): district names repeat across cities.
   */
  district_key: string | null;
  engine_condition: string | null;
  engine_volume_cc: number | null;
  fuel: string | null;
  gearbox: string | null;
  gearbox_condition: string | null;
  has_photo: boolean | null;
  insurance_months_left: number | null;
  last_seen_at: Timestamp | null;
  listed_at: Timestamp | null;
  listing_id: number | null;
  make_id: number | null;
  /**
   * The make's slug: the value a URL and a stored search name it by.
   */
  make_key: string | null;
  market_value_toman: number | null;
  mileage_km: number | null;
  model_id: number | null;
  /**
   * make slug.model slug (peugeot.206): model slugs are unique only within their make.
   */
  model_key: string | null;
  /**
   * The model's place by active listings, 1 the most listed; how popular, and so how easy to service and resell, the model is.
   */
  model_rank: number | null;
  model_year_sh: number | null;
  /**
   * true when the site's field or the text offers instalments, or the shown price is a down payment; false when either refuses; else null.
   */
  offers_installments: boolean | null;
  /**
   * true when the site's field or the text says the seller takes a car in exchange; false when either refuses; else null.
   */
  offers_swap: boolean | null;
  /**
   * false when the seller rates the body repainted, accident-damaged or salvage, or the text states any paint, a spot included; true when the body is rated intact, scratched or dent-repaired without paint, or the text says unpainted; null when neither says.
   */
  paint_free: boolean | null;
  /**
   * The text's plate fact: national or free_zone; null when not stated or not accepted.
   */
  plate: string | null;
  price_gap_pct: Numeric | null;
  price_type: string | null;
  /**
   * The text's replaced fact (CS-52): some or none; null when not stated or not accepted.
   */
  replaced_parts: string | null;
  /**
   * The text's ride_hailing fact: used or not_used; null when not stated or not accepted.
   */
  ride_hailing: string | null;
  seller_type: string | null;
  source_id: string | null;
  status: string | null;
  trim_id: number | null;
  /**
   * make slug.model slug.trim slug (peugeot.206.5); null when the catalogue knows only the model.
   */
  trim_key: string | null;
}

export interface ListingMark {
  account_id: number;
  created_at: Generated<Timestamp>;
  listing_id: number;
  /**
   * The listing's asking price when it was marked, in whole tomans; NULL when it had none (negotiable, instalment, placeholder). The page compares it with today's price.
   */
  marked_price_toman: number | null;
  /**
   * The newest listing_price_event of the listing that existed when the buyer marked it, then the newest one marks.notify has handled for this mark; it looks only at events after it. Events of one listing commit in id order (listing_price_event_fill_previous holds the listing's row), so none is passed over.
   */
  price_event_seen_id: Generated<number>;
  /**
   * The listing status the buyer was last shown or told: marks.notify notifies when the listing's status differs from it by going off the market (sold, expired, gone) or coming back (active), then sets it.
   */
  seen_status: "active" | "sold" | "expired" | "gone" | "removed";
  /**
   * How many status changes marks.notify has announced for this mark; part of the notification's event key, so the same listing can be announced again when it goes off the market a second time.
   */
  status_version: Generated<number>;
}

export interface ListingPhoto {
  listing_id: number;
  /**
   * The photo's place in the source's order, from 1: the first is the listing's main photo.
   */
  position: number;
  /**
   * The source's own small version of the same photo, for result cards; null when the source gives none.
   */
  thumbnail_url: string | null;
  /**
   * The full-size photo's address on the source's photo host, which pages load it from.
   */
  url: string;
}

export interface ListingPriceEvent {
  /**
   * The asking price in whole tomans, exactly when price_type is asking.
   */
  asking_price_toman: number | null;
  /**
   * The list page's request that showed this price in the listing's row (a sweep or discovery page); NULL when the evidence is a snapshot. Exactly one of the two is set.
   */
  fetch_log_id: number | null;
  id: ColumnType<number, never, never>;
  /**
   * The latest earlier asking price, filled by the trigger, across negotiable and placeholder events: an asking price below it is a drop.
   */
  last_asking_price_toman: ColumnType<number | null, never, never>;
  listing_id: number;
  /**
   * When the source showed this price: the start of the request that is the evidence, the listing's page (snapshot_id) or the list page (fetch_log_id).
   */
  observed_at: Timestamp;
  /**
   * The previous event's asking price, filled by the trigger; null when that event carried none.
   */
  previous_price_toman: ColumnType<number | null, never, never>;
  /**
   * The type of the listing's previous event, filled by the trigger; null for its first.
   */
  previous_price_type: ColumnType<"asking" | "negotiable" | "installment" | "placeholder" | null, never, never>;
  /**
   * asking (an amount), negotiable («توافقی»), installment (an installment offer: its figure is not the car's price), placeholder (a token figure such as 1,000 tomans); only asking carries an amount.
   */
  price_type: "asking" | "negotiable" | "installment" | "placeholder";
  /**
   * When we stored the event; differs from observed_at when history is re-derived.
   */
  recorded_at: Generated<Timestamp>;
  /**
   * The snapshot of the listing's page that showed this price; NULL when the evidence is a list row (fetch_log_id).
   */
  snapshot_id: number | null;
}

export interface ListingRecheckRequest {
  /**
   * When the worker handled the request; NULL while pending.
   */
  handled_at: Timestamp | null;
  id: ColumnType<number, never, never>;
  listing_id: number;
  /**
   * What became of it: queued (a re-check job was sent), fresh (the listing's page was read within the freshness window, six hours) or off_market (the listing had already left the market).
   */
  outcome: "queued" | "fresh" | "off_market" | null;
  requested_at: Generated<Timestamp>;
}

export interface ListingStatusTransition {
  from_status: string;
  origin: "external" | "native";
  to_status: string;
}

export interface ListingUnparsedValue {
  /**
   * The attribute the value would fill: model_year (model_year_written, _sh and _ad), price (price_type and its amounts), chassis_condition (front and rear), or the listing column of that name.
   */
  field: "model_year" | "mileage_km" | "fuel" | "gearbox" | "insurance_months_left" | "price" | "accepts_swap" | "accepts_installments" | "seller_type" | "body_condition" | "engine_condition" | "gearbox_condition" | "chassis_condition" | "colour";
  listing_id: number;
  /**
   * The value exactly as the source wrote it, direction marks and all.
   */
  raw_text: string;
}

export interface ListingValuation {
  /**
   * The asking price that was rated, as the listing showed it when the run read it; null when its price type is not asking.
   */
  asking_price_toman: number | null;
  deal_rating: DealRating | null;
  listing_id: number;
  /**
   * The market value on the run's day; null when the listing's model, attributes or condition cannot be valued. A negotiable listing keeps its value but no rating.
   */
  market_value_toman: number | null;
  no_rating_reason: "unmatched_model" | "missing_attributes" | "excluded_condition" | "too_few_comparables" | "uncertain_segment" | "year_out_of_range" | "unknown_price" | "no_asking_price" | "placeholder_price" | "installment_price" | "dealer_new_car" | "price_outlier" | null;
  /**
   * (asking - market value) / market value, in percent; negative is cheaper than the market.
   */
  price_gap_pct: Numeric | null;
  valuation_run_id: number;
}

export interface ListingValuationComparable {
  adjusted_price_toman: number;
  asking_price_toman: number;
  comparable_listing_id: number;
  listing_id: number;
  position: number;
  valuation_run_id: number;
}

export interface Make {
  created_at: Generated<Timestamp>;
  id: ColumnType<number, never, never>;
  name_en: string;
  name_fa: string | null;
  slug: string;
}

export interface Model {
  body_type: string | null;
  created_at: Generated<Timestamp>;
  id: ColumnType<number, never, never>;
  make_id: number;
  name_en: string;
  name_fa: string | null;
  slug: string;
}

export interface ModelDemand {
  /**
   * The Tehran day.
   */
  demand_date: Timestamp;
  id: ColumnType<number, never, never>;
  kind: "search" | "paste";
  model_id: number;
  /**
   * Requests that day, capped at 1,000,000.
   */
  request_count: Generated<number>;
}

export interface ModelPhotoLink {
  model_id: number;
  set_at: Generated<Timestamp>;
  /**
   * The superadmin who last set or replaced the link.
   */
  set_by_account_id: number;
  /**
   * The image's own address: https, a dotted host, at most 500 characters, plain characters only. Its being an image is the superadmin's to confirm in the preview; the page falls back to the body type's photograph when it does not load.
   */
  url: string;
}

export interface ModelPhotoLinkChange {
  action: "set" | "replaced" | "cleared";
  by_account_id: number;
  changed_at: Generated<Timestamp>;
  from_url: string | null;
  id: ColumnType<number, never, never>;
  model_id: number;
  to_url: string | null;
}

export interface ModelSpec {
  /**
   * domestic: an Iranian maker's own design (Pride, Samand, Dena); joint_venture: a foreign design built in Iran under licence or partnership (Peugeot 206, 405); imported: built abroad and brought in. Null when unknown.
   */
  car_origin: "domestic" | "joint_venture" | "imported" | null;
  /**
   * Nominal engine volume in cubic centimetres (500 to 9000), the figure buyers type («۱۶۰۰»), not the exact displacement; null when only the origin is known.
   */
  engine_volume_cc: number | null;
  id: ColumnType<number, never, never>;
  model_id: number;
  set_at: Generated<Timestamp>;
  set_by_account_id: number | null;
  /**
   * catalogue: the trim's own name states the volume; seed: written by CS-99 from the makers' published engines; superadmin: entered in the superadmin section.
   */
  source: "catalogue" | "seed" | "superadmin";
  trim_id: number | null;
}

export interface ModelSpecAgreed {
  engine_volume_cc: number | null;
  model_id: number | null;
}

export interface ModelSpecChange {
  action: "seeded" | "added" | "changed" | "removed";
  by_account_id: number | null;
  changed_at: Generated<Timestamp>;
  from_origin: string | null;
  from_volume_cc: number | null;
  id: ColumnType<number, never, never>;
  model_id: number;
  to_origin: string | null;
  to_volume_cc: number | null;
  trim_id: number | null;
}

export interface ModelSpend {
  /**
   * Millionths of a US dollar at Metis's price, every attempt of the call included.
   */
  cost_usd_micros: number;
  created_at: Generated<Timestamp>;
  error_reason: "timeout" | "aborted" | "rate_limited" | "unavailable" | "unauthorized" | "no_credit" | "rejected" | null;
  /**
   * True when the layer could not measure the cost (an attempt that got no answer, a model with no price) and the caller counted its estimate.
   */
  estimated: boolean;
  id: ColumnType<number, never, never>;
  model: string;
  outcome: "ok" | "invalid" | "refusal" | "truncated" | "empty" | "error";
  prompt_version: string;
  /**
   * The snapshot the call read, for a listing step; how often its calls failed decides when it goes to review.
   */
  snapshot_id: number | null;
  task: string;
}

export interface ModelVolume {
  /**
   * Listings the walk read in the slice, promoted rows counted once.
   */
  active_count: number;
  /**
   * Whether the walk reached the end of the slice; false when the source stopped answering pages first or the walk hit its page limit, and then active_count is a lower bound.
   */
  complete: boolean;
  id: ColumnType<number, never, never>;
  /**
   * all (every car), brand, model or trim: how finely the slice is cut.
   */
  level: "all" | "brand" | "model" | "trim";
  /**
   * List pages the walk read: how deep the source let it follow the slice.
   */
  pages_read: number;
  source_id: string;
  /**
   * The source's own filter value for the slice, as its search takes it (Divar's brand_model: ROOT, Peugeot, Peugeot 206, Peugeot 206 5); mapped to the catalogue when CS-50 knows it.
   */
  source_model_key: string;
  /**
   * When the sweep (or measurement) that counted it started: it groups one sweep's slices.
   */
  swept_at: Timestamp;
}

export interface Notification {
  account_id: number;
  created_at: Generated<Timestamp>;
  /**
   * Names the event this notification announces, built by the kind's definition from its payload (price_event:812, crawl_request:31:approved); with the account and the kind it is unique, so a producer that runs twice notifies once.
   */
  event_key: string;
  id: ColumnType<number, never, never>;
  kind: string;
  /**
   * The listing it is about, for a listing's kinds; search files and crawl requests get columns of their own with their tables (CS-70, CS-71).
   */
  listing_id: number | null;
  /**
   * The facts the notification was built from, when it was created (a car's name, the price before and after), as the kind's schema in packages/notifications defines them; never personal data.
   */
  payload: Json;
  /**
   * When the buyer read it or marked it read; NULL while unread. The only column the web app may change.
   */
  read_at: Timestamp | null;
  /**
   * The search file it is about, for the search file kinds; a deleted file takes its notifications.
   */
  search_file_id: number | null;
}

export interface NotificationKind {
  created_at: Generated<Timestamp>;
  /**
   * What the kind announces, in English, for people reading the database; the Farsi a buyer reads is built in code.
   */
  description: string;
  id: string;
}

export interface NotificationMute {
  account_id: number;
  created_at: Generated<Timestamp>;
  id: ColumnType<number, never, never>;
  kind: string;
}

export interface ReviewItem {
  closed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  extraction_id: number | null;
  field: string | null;
  id: ColumnType<number, never, never>;
  kind: "extraction_field" | "extraction_held" | "answer_invalid";
  outcome: "invalid" | "refusal" | "truncated" | "empty" | "error" | null;
  /**
   * The layer's problems for an answer that never validated: [{path, message}], each naming the field, the value seen and what is admissible; for outcome error, why no answer came after repeated calls.
   */
  problems: Json | null;
  prompt_version: string | null;
  snapshot_id: number | null;
  status: Generated<"open" | "resolved" | "dismissed">;
  task: string | null;
}

export interface SchemaMigrations {
  version: string;
}

export interface SearchBuildEvent {
  event: "documents_changed" | "counts_built" | "vocabulary_built" | "full_rebuild";
  happened_at: Timestamp;
}

export interface SearchDocument {
  accident: string | null;
  asking_price_toman: number | null;
  body_condition: string | null;
  body_type: string | null;
  /**
   * domestic, joint_venture or imported: the listing's trim's origin, else its model's (model_spec); null when unknown.
   */
  car_origin: "domestic" | "joint_venture" | "imported" | null;
  chassis_condition: string | null;
  city_id: number | null;
  city_key: string | null;
  colour_family: string | null;
  /**
   * The first photo's address on the source's own host (listing_photo, ADR-0025): shown from there, never stored.
   */
  cover_photo_url: string | null;
  cover_thumbnail_url: string | null;
  deal_rating: DealRating | null;
  district_fa: string | null;
  district_key: string | null;
  engine_condition: string | null;
  /**
   * The listing's engine volume in cc: its own title's, else its trim's, else its model's (model_spec); null when unknown, and then excluded by a volume filter.
   */
  engine_volume_cc: number | null;
  fuel: string | null;
  gearbox: string | null;
  gearbox_condition: string | null;
  has_photo: boolean;
  /**
   * When the listing first became searchable (CS-72): set by the insert, never by the build's update, so it is the instant the listing first appeared in search. A row that expires and is built again starts again. A file's new matches are the rows indexed after its baseline.
   */
  indexed_at: Generated<Timestamp>;
  insurance_months_left: number | null;
  /**
   * mileage_km per year of age in the build's Solar Hijri year, a car under a year counted as half a year (S01), rounded: what «کم‌کارکرد نسبت به سن» reads, shown on a card.
   */
  km_per_year: number | null;
  /**
   * When a crawl last saw the listing: a search shows it only within 48 hours of this (ADR-0017 point 6), and the worker expires the row after that.
   */
  last_seen_at: Timestamp;
  listed_at: Timestamp;
  listing_id: number;
  make_id: number | null;
  make_key: string | null;
  market_value_toman: number | null;
  mileage_km: number | null;
  model_id: number | null;
  model_key: string | null;
  model_rank: number | null;
  model_year_sh: number | null;
  offers_installments: boolean | null;
  offers_swap: boolean | null;
  paint_free: boolean | null;
  /**
   * How many photos the listing's latest snapshot has (ADR-0025).
   */
  photo_count: number;
  plate: string | null;
  /**
   * The asking price's distance from market value in percent, negative below it, from the latest succeeded valuation run (CS-51); null when unrated. The default order leads with it.
   */
  price_gap_pct: Numeric | null;
  /**
   * How the listing states its price (asking, negotiable, installment, placeholder). Set exactly when the listing's details have been read, so it is what makes a listing searchable.
   */
  price_type: string;
  /**
   * When the row last changed.
   */
  refreshed_at: Timestamp;
  replaced_parts: string | null;
  ride_hailing: string | null;
  /**
   * What a query matches, as written: the title, the make, model and trim names in Persian and English with their curated and suggested aliases, the model year in both calendars, the city, district, colour and body type. Never shown.
   */
  search_text: string;
  seller_type: string | null;
  source_id: string;
  /**
   * search_text normalised by search_normalize, as fa_search lexemes: computed only when a row is written, and searched through search_query().
   */
  text_vector: ColumnType<string, never, never>;
  trim_id: number | null;
  trim_key: string | null;
  /**
   * as_of_date of the valuation run the rating comes from; null when unrated.
   */
  valued_on: Timestamp | null;
}

export interface SearchDocumentStale {
  id: ColumnType<number, never, never>;
  listing_id: number;
  marked_at: Generated<Timestamp>;
}

export interface SearchFacetCount {
  /**
   * When this count last changed.
   */
  changed_at: Timestamp;
  /**
   * total: the listings in search_document. seen: the active listings of public sources a crawl saw in the last 48 hours, whether or not their details were read; the difference is what is not yet searchable.
   */
  facet: "total" | "seen" | "catalogue" | "make" | "model" | "trim" | "body_type" | "city" | "district" | "source";
  /**
   * The option's Persian name (the English one where the catalogue has none yet).
   */
  label_fa: string;
  listing_count: number;
  /**
   * The option's place within its facet: the catalogue's order for body types and catalogues, most listed first for the others.
   */
  position: number;
  /**
   * The option's value as a URL and a stored search name it (make slug, make.model, city.district, a catalogue id); empty for total and seen.
   */
  value: string;
}

export interface SearchFile {
  account_id: number;
  created_at: Generated<Timestamp>;
  id: ColumnType<number, never, never>;
  /**
   * When the matching job last notified the buyer about this file (NULL: never).
   */
  last_alert_at: Timestamp | null;
  /**
   * The matching job's watermark (CS-72): every listing indexed up to this instant was matched against the file, and the buyer told if it was watched and unmuted. Starts at the file's creation, so what the search showed then is not alerted; advanced for paused, closed and muted files too, so a buyer who resumes is not flooded; held back only when the account's daily cap is reached, so the next run tells the whole backlog in one digest.
   */
  matched_through: Generated<Timestamp>;
  /**
   * When the buyer turned off alerts for this file (NULL: alerts on). The file keeps matching and showing what is new; create_notification() creates nothing for a muted file.
   */
  muted_at: Timestamp | null;
  /**
   * What the buyer calls the file: suggested from the search («پژو ۲۰۶ تیپ ۵ تا ۷۰۰ میلیون»), changed by the buyer. Trimmed, 1 to 80 characters. Not unique: the search is.
   */
  name: string;
  /**
   * The look before viewed_at that was more than 5 minutes earlier: looks within 5 minutes of each other are one visit, so a refresh or a quick return still shows what was new when the visit began. A match Carshenas first saw (listing.created_at) after the baseline is new to the buyer, the baseline being previous_viewed_at while viewed_at is under 5 minutes old and viewed_at after that (searchFileSeenBaseline in apps/web/src/server/db/sql-helpers.ts).
   */
  previous_viewed_at: Generated<Timestamp>;
  /**
   * The search as @carshenas/search stores it (StoredSearch, ADR-0027): {"v": 1, "q"?, "filters": {…}, "sort"?, "catalogue"?}, canonical, a catalogue always expanded to its filters, so two equal searches are equal jsonb. Read it back with fromStoredSearch(), which checks it against the filters of the build that reads it; a row that no longer fits is shown as such, never guessed. Fixed once written: a changed search is a new file. CS-71 reads the make, model and trim keys from filters.make, filters.model and filters.trim.
   */
  search: Json;
  /**
   * watching: Karshenas keeps looking and tells the buyer what is new (CS-72); paused: kept, not watched; closed: the buyer found a car or no longer wants it, kept to look back on. The buyer moves it between the three freely.
   */
  status: Generated<"watching" | "paused" | "closed">;
  /**
   * When the state last changed (the creation time at first).
   */
  status_changed_at: Generated<Timestamp>;
  /**
   * When the buyer last left the file's page. The creation time at first, so what the search showed when it was saved is not new.
   */
  viewed_at: Generated<Timestamp>;
}

export interface SearchWord {
  /**
   * How many searchable listings have the word: a correction needs a common word, and prefers the more common of two equally close ones.
   */
  listing_count: number;
  word: string;
}

export interface Snapshot {
  /**
   * Version of the crawler's canonical form. A new version may re-express an unchanged page as new JSON, which is then a new snapshot; identical JSON is one snapshot whatever the version.
   */
  canonical_version: number;
  /**
   * Computed by the database from payload, so the deduplication key can never disagree with the content.
   */
  content_sha256: ColumnType<Buffer, never, never>;
  /**
   * When this content was first fetched; later identical fetches point here from fetch_log.
   */
  first_fetched_at: Timestamp;
  id: ColumnType<number, never, never>;
  listing_id: number;
  /**
   * What the page showed, as canonical JSON: phone numbers and other personal data are removed before storage (ADR-0008 point 7). Compressed with lz4 through default_toast_compression (db/postgresql.conf).
   */
  payload: Json;
  url: string;
}

export interface Source {
  /**
   * crawl: our crawler reads the source's pages or public web API within ADR-0008 (Divar through its web API, by the owner's decision of 2026-09-27); official_api: single items through a partner API the source grants; native: our own database.
   */
  access_method: "crawl" | "official_api" | "native";
  base_url: string;
  /**
   * enabled or paused by a human; stopped_on_block by the crawler on a 401 or 403, a challenge, or a second 429 within 24 hours (ADR-0008 point 6, ADR-0018), until a human reads the evidence and re-enables it.
   */
  crawl_state: Generated<"enabled" | "paused" | "stopped_on_block">;
  created_at: Generated<Timestamp>;
  /**
   * Requests this source may receive in one Tehran day (ADR-0017 point 5): at most half of what min_request_interval_ms allows in a day, spent in ADR-0017's priority order, what comes last dropped first. Divar: 12,000 (owner, 2026-09-30). Set by migrations or the owner; the worker only reads it.
   */
  daily_request_budget: number | null;
  /**
   * Stable code used in URLs, logs and job names, for example bama.
   */
  id: string;
  /**
   * public: its listings appear in search; requester_only: a source whose rules allow reading a pasted link but not publishing it, shown only to the buyer who pasted it (CS-19).
   */
  listing_visibility: "public" | "requester_only";
  /**
   * Milliseconds between two requests to this source; at least 3000 for crawled sources (ADR-0008 point 5). robots.txt is recorded, not followed, so a Crawl-delay does not lengthen it; the lane waits longer after a slow answer and after a 429 (ADR-0018).
   */
  min_request_interval_ms: number | null;
  name_fa: string;
  /**
   * external: listings on other sites; native: listings created on Carshenas; benchmark: published price tables, never listings.
   */
  origin: "external" | "native" | "benchmark";
  /**
   * How many days old the latest policy check may be before a crawl is refused.
   */
  policy_max_age_days: Generated<number>;
  stop_reason: "blocked" | "rate_limited" | "challenge" | null;
  /**
   * When the crawler stopped the source: the requested_at of the blocked request in fetch_log, which is the evidence.
   */
  stopped_at: Timestamp | null;
}

export interface SourceCurrentPolicy {
  checked_at: Timestamp | null;
  checked_by: string | null;
  conditions: string | null;
  id: number | null;
  photos_allowed: boolean | null;
  source_id: string | null;
  verdict: string | null;
}

export interface SourceDailySpend {
  daily_request_budget: number | null;
  kind: "discovery" | "detail" | "measure" | "sweep" | "check" | "recheck" | null;
  outcome: "ok" | "not_modified" | "not_found" | "gone" | "blocked" | "rate_limited" | "challenge" | "error" | null;
  requests: number | null;
  source_id: string | null;
  tehran_day: Timestamp | null;
}

export interface SourcePolicyCheck {
  checked_at: Timestamp;
  checked_by: string;
  conditions: string | null;
  id: ColumnType<number, never, never>;
  /**
   * Whether this source's terms allow downloading and re-hosting its photos, as read. Nothing is downloaded or re-hosted (ADR-0025), so it does not decide whether pages show a source's photos from their addresses.
   */
  photos_allowed: boolean;
  /**
   * The robots.txt text as read, kept as evidence.
   */
  robots_txt: string | null;
  source_id: string;
  terms_summary: string;
  terms_url: string | null;
  verdict: "allowed" | "allowed_with_conditions" | "not_allowed";
}

export interface SourceStateChange {
  /**
   * When the change took effect: the moment change_source_state() applied it, holding the source's lock (clock_timestamp(), not the transaction's start), so the order of a source's changes is the order they took effect.
   */
  changed_at: Generated<Timestamp>;
  /**
   * The superadmin who made the change; change_source_state() refuses any other account.
   */
  changed_by_account_id: number;
  /**
   * For a change away from stopped_on_block, why the crawler had stopped the source: source.stop_reason.
   */
  cleared_stop_reason: "blocked" | "rate_limited" | "challenge" | null;
  /**
   * For a change away from stopped_on_block, the stop it cleared: source.stopped_at, the start of the blocked request in fetch_log.
   */
  cleared_stopped_at: Timestamp | null;
  /**
   * source.crawl_state before the change.
   */
  from_state: "enabled" | "paused" | "stopped_on_block";
  id: ColumnType<number, never, never>;
  source_id: string;
  /**
   * source.crawl_state after it: enabled or paused. Only the crawler stops a source (stop_source()).
   */
  to_state: "enabled" | "paused";
}

export interface TrackedBackfill {
  /**
   * How many times the job started; pg-boss retries a failed job three times, so four means it gave up.
   */
  attempts: Generated<number>;
  last_attempt_at: Timestamp | null;
  listing_id: number;
  queued_at: Generated<Timestamp>;
}

export interface TrackedModel {
  /**
   * The approved crawl request the row answers: the one that made it (origin request), or one an approval attached to a model that was tracked already. NULL when none.
   */
  crawl_request_id: number | null;
  created_at: Generated<Timestamp>;
  /**
   * The superadmin who tracked it, or who approved the request that made it; NULL for the seed.
   */
  created_by_account_id: number | null;
  id: ColumnType<number, never, never>;
  model_id: number;
  /**
   * How the row came to be: seed (the owner's first ten), superadmin (chosen in the section by created_by_account_id) or request (the approval, by created_by_account_id, of crawl_request_id).
   */
  origin: "seed" | "superadmin" | "request";
  /**
   * high, normal or low: the order the worker sweeps models and backfills their listings in, and how much of a tier of the daily budget each takes first (never a promise of more requests).
   */
  priority: Generated<"high" | "normal" | "low">;
  state: Generated<"tracking" | "paused">;
  /**
   * NULL tracks the whole model; a trim tracks that trim only.
   */
  trim_id: number | null;
  /**
   * When the row last changed (state or priority), by the database's clock.
   */
  updated_at: Generated<Timestamp>;
  updated_by_account_id: number | null;
}

export interface TrackedModelChange {
  action: "seeded" | "tracked" | "from_request" | "paused" | "resumed" | "priority_changed" | "untracked" | "request_withdrawn";
  by_account_id: number | null;
  changed_at: Generated<Timestamp>;
  crawl_request_id: number | null;
  /**
   * The state (paused, tracking) or priority before the change, where the action changes one.
   */
  from_value: string | null;
  id: ColumnType<number, never, never>;
  model_id: number;
  /**
   * The state or priority after the change.
   */
  to_value: string | null;
  trim_id: number | null;
}

export interface TrackedModelScope {
  model_id: number | null;
  trim_id: number | null;
}

export interface Trim {
  body_type: string | null;
  created_at: Generated<Timestamp>;
  id: ColumnType<number, never, never>;
  model_id: number;
  name_en: string;
  name_fa: string | null;
  slug: string;
}

export interface ValuationCoefficient {
  /**
   * On the log scale: a shared term adds it once per unit of its feature; model_age_slope is the model's whole slope per year of age.
   */
  coefficient: number;
  id: ColumnType<number, never, never>;
  model_id: number | null;
  term: "model_level" | "model_age_slope" | "trim_level" | "age_slope" | "mileage_deviation" | "zero_km" | "body_minor" | "body_painted" | "body_painted_around" | "chassis_repainted" | "gearbox_automatic" | "dual_fuel_aftermarket" | "electrified" | "off_colour" | "day";
  trim_id: number | null;
  valuation_run_id: number;
}

export interface ValuationComparable {
  asking_price_toman: number;
  fitted_value_toman: number;
  is_outlier: boolean;
  listing_id: number;
  mileage_km: number;
  model_id: number;
  model_year_sh: number;
  valuation_run_id: number;
}

export interface ValuationRun {
  /**
   * The Tehran day the market values hold for.
   */
  as_of_date: Timestamp;
  comparable_count: number | null;
  finished_at: Timestamp | null;
  id: ColumnType<number, never, never>;
  method_version: number;
  /**
   * Kilometres a year the market treats as normal (20,000 in method 1): mileage is measured against it.
   */
  mileage_norm_km_per_year: number;
  /**
   * How many listings each coefficient's prior weighs in the ridge fit.
   */
  prior_strength: number;
  rated_count: number | null;
  /**
   * The Jalali year of as_of_date: a car's age is this minus its model_year_sh, floored at 0.
   */
  reference_year_sh: number;
  started_at: Generated<Timestamp>;
  status: "running" | "succeeded" | "failed";
  valued_count: number | null;
  /**
   * How many days before as_of_date a listing may have last been seen and still be a comparable.
   */
  window_days: number;
}

export interface ValuationSegment {
  comparable_count: number;
  /**
   * Median absolute percentage error of the model's comparables, each valued by the fit without itself (leave-one-out); null when too few to measure.
   */
  error_pct: Numeric | null;
  max_model_year_sh: number;
  min_model_year_sh: number;
  model_id: number;
  rates_listings: boolean;
  valuation_run_id: number;
  /**
   * How many of its comparables (outliers left out) are zero-km, under 1,000 km.
   */
  zero_km_count: number;
}

export interface WantedLink {
  first_wanted_at: Generated<Timestamp>;
  id: ColumnType<number, never, never>;
  last_wanted_at: Generated<Timestamp>;
  /**
   * How many times it was pasted, capped at 1,000,000.
   */
  request_count: Generated<number>;
  source_id: string;
  /**
   * The source's token as the listing table keeps it (listing.source_listing_key), taken from the pasted address by code.
   */
  source_listing_key: string;
}

export interface WorkerHeartbeat {
  /**
   * The last beat, by the database's clock (now() of the beat), so a server's drifting clock cannot fake one.
   */
  beat_at: Timestamp;
  hostname: string;
  id: ColumnType<number, never, never>;
  /**
   * Chosen by the process when it starts; names it in the section.
   */
  instance_id: string;
  pid: number;
  /**
   * When the process started, by the database's clock.
   */
  started_at: Timestamp;
  /**
   * When the process shut down cleanly; null while it runs or when it died without saying so.
   */
  stopped_at: Timestamp | null;
  /**
   * The release the process runs: CARSHENAS_RELEASE, or the commit.
   */
  version: string;
}

export interface DB {
  account: Account;
  account_role_change: AccountRoleChange;
  account_session: AccountSession;
  ai_answer: AiAnswer;
  ai_evaluation: AiEvaluation;
  auth_throttle: AuthThrottle;
  body_type: BodyType;
  catalogue_alias: CatalogueAlias;
  catalogue_source_key: CatalogueSourceKey;
  city: City;
  colour: Colour;
  crawl_feed: CrawlFeed;
  crawl_lane: CrawlLane;
  crawl_request: CrawlRequest;
  crawl_request_decision: CrawlRequestDecision;
  crawl_request_file: CrawlRequestFile;
  crawl_run: CrawlRun;
  extraction: Extraction;
  extraction_field: ExtractionField;
  extraction_field_def: ExtractionFieldDef;
  fetch_log: FetchLog;
  freshness_measurement: FreshnessMeasurement;
  job_state_change: JobStateChange;
  listing: Listing;
  listing_fact_evidence: ListingFactEvidence;
  listing_filter_row: ListingFilterRow;
  listing_mark: ListingMark;
  listing_photo: ListingPhoto;
  listing_price_event: ListingPriceEvent;
  listing_recheck_request: ListingRecheckRequest;
  listing_status_transition: ListingStatusTransition;
  listing_unparsed_value: ListingUnparsedValue;
  listing_valuation: ListingValuation;
  listing_valuation_comparable: ListingValuationComparable;
  make: Make;
  model: Model;
  model_demand: ModelDemand;
  model_photo_link: ModelPhotoLink;
  model_photo_link_change: ModelPhotoLinkChange;
  model_spec: ModelSpec;
  model_spec_agreed: ModelSpecAgreed;
  model_spec_change: ModelSpecChange;
  model_spend: ModelSpend;
  model_volume: ModelVolume;
  notification: Notification;
  notification_kind: NotificationKind;
  notification_mute: NotificationMute;
  review_item: ReviewItem;
  schema_migrations: SchemaMigrations;
  search_build_event: SearchBuildEvent;
  search_document: SearchDocument;
  search_document_stale: SearchDocumentStale;
  search_facet_count: SearchFacetCount;
  search_file: SearchFile;
  search_word: SearchWord;
  snapshot: Snapshot;
  source: Source;
  source_current_policy: SourceCurrentPolicy;
  source_daily_spend: SourceDailySpend;
  source_policy_check: SourcePolicyCheck;
  source_state_change: SourceStateChange;
  tracked_backfill: TrackedBackfill;
  tracked_model: TrackedModel;
  tracked_model_change: TrackedModelChange;
  tracked_model_scope: TrackedModelScope;
  trim: Trim;
  valuation_coefficient: ValuationCoefficient;
  valuation_comparable: ValuationComparable;
  valuation_run: ValuationRun;
  valuation_segment: ValuationSegment;
  wanted_link: WantedLink;
  worker_heartbeat: WorkerHeartbeat;
}
