// Prints the SQL that installs or upgrades pg-boss's schema, for a dbmate migration (ADR-0018 point 7): the queue's
// tables belong to carshenas_owner like every other object, and the worker runs pg-boss with `migrate: false`, so it
// only needs row access. Paste the output into a file from `pnpm db:new`, after the house template's timeouts.
//
//   pnpm --filter @carshenas/worker pgboss:sql install                   the whole schema, for an empty database
//   pnpm --filter @carshenas/worker pgboss:sql upgrade <version>          from an installed schema version to this
//                                                                          package's, as one migration
//   pnpm --filter @carshenas/worker pgboss:sql upgrade <version> --split  the same in ordered parts, when it builds
//                                                                          indexes CONCURRENTLY
//
// An upgrade that builds indexes CONCURRENTLY cannot run inside a migration's transaction (25001). It is printed only
// with --split, in the order it must run: transactional parts, and each concurrent statement alone in a
// `-- migrate:up transaction:false` file with the two Squawk comments (the database skill, "Migrations").
//
// pg-boss wraps its plans in BEGIN, SET LOCAL timeouts and COMMIT; dbmate runs each migration in its own
// transaction with the template's timeouts, so those lines are left out. So is the block that creates today's and
// tomorrow's partitions of queue_stats: they serve only `persistQueueStats`, which stays off because the worker
// cannot create the next days' partitions (no DDL rights), and date-named tables would change db/schema.sql every
// day. Everything else is pg-boss's text as is.
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { getConstructionPlans, getMigrationPlans } from 'pg-boss';
import { ensureQueueStatsPartitions } from 'pg-boss/dist/plans.js';

const SCHEMA = 'pgboss';
const require = createRequire(import.meta.url);
const { version, pgboss } = JSON.parse(readFileSync(require.resolve('pg-boss/package.json'), 'utf8'));

const WRAPPER = [
  /^\s*BEGIN;\s*$/,
  /^\s*SET LOCAL lock_timeout = \d+;\s*$/,
  /^\s*SET LOCAL idle_in_transaction_session_timeout = \d+;\s*$/,
  /^\s*COMMIT;\s*$/,
];

function unwrap(plan) {
  return plan
    .split('\n')
    .filter((line) => !WRAPPER.some((pattern) => pattern.test(line)))
    .join('\n')
    .trim();
}

const CONCURRENT = /^\s*(CREATE|DROP)\s+(UNIQUE\s+)?INDEX\s+CONCURRENTLY\b/i;

/** The plan in the order it must run: runs of transactional lines, and each concurrent statement on its own. */
function parts(body) {
  const result = [];
  let current = [];
  for (const line of body.split('\n')) {
    if (CONCURRENT.test(line)) {
      assert.ok(
        line.trim().endsWith(';'),
        `a concurrent statement spans lines, split it by hand: ${line.trim()}`,
      );
      if (current.join('').trim() !== '') result.push({ concurrent: false, sql: current.join('\n').trim() });
      result.push({ concurrent: true, sql: line.trim() });
      current = [];
    } else {
      current.push(line);
    }
  }
  if (current.join('').trim() !== '') result.push({ concurrent: false, sql: current.join('\n').trim() });
  return result;
}

const [command, from, flag] = process.argv.slice(2);
let body;
if (command === 'install') {
  // The schema itself is created by the migration, without IF NOT EXISTS (the database skill: no IF [NOT] EXISTS).
  const plan = getConstructionPlans(SCHEMA, { createSchema: false });
  const partitions = ensureQueueStatsPartitions(SCHEMA);
  assert.ok(
    plan.includes(partitions),
    'pg-boss no longer creates queue_stats partitions this way: review the plan by hand',
  );
  body = unwrap(plan.replace(partitions, ''));
} else if (command === 'upgrade' && /^\d+$/.test(from ?? '')) {
  body = unwrap(getMigrationPlans(SCHEMA, Number(from)));
} else {
  process.stderr.write('usage: pgboss-sql.mjs install | upgrade <installed schema version>\n');
  process.exit(2);
}

const header =
  `-- Generated by \`pnpm --filter @carshenas/worker pgboss:sql ${process.argv.slice(2).join(' ')}\` from pg-boss ${version} ` +
  `(schema version ${pgboss.schema}); regenerate rather than edit.`;
const planParts = parts(body);
if (!planParts.some((part) => part.concurrent)) {
  process.stdout.write(`${header}\n${body}\n`);
} else if (flag !== '--split') {
  process.stderr.write(
    `This upgrade builds ${planParts.filter((part) => part.concurrent).length} index(es) CONCURRENTLY, which cannot run ` +
      "inside a migration's transaction. Run it again with --split and make one migration per part, in order.\n",
  );
  process.exit(1);
} else {
  planParts.forEach((part, index) => {
    const kind = part.concurrent
      ? '-- migrate:up transaction:false\n-- squawk-disable-assume-in-transaction\n-- squawk-ignore require-lock-timeout, require-statement-timeout'
      : "-- migrate:up (below the template's SET LOCAL timeouts)";
    process.stdout.write(
      `-- ===== part ${index + 1} of ${planParts.length} =====\n${kind}\n${header}\n${part.sql}\n\n`,
    );
  });
}
