import 'server-only';
import { Kysely, PostgresDialect, type LogEvent } from 'kysely';
import type { ReadonlyKysely } from 'kysely/readonly';
import pg from 'pg';
import type { DB } from '@/server/db/db-types';
import { env } from '@/server/env';
import { captureError, logger } from '@/server/observability/logger';

// The web app's only way into PostgreSQL (ADR-0012): one pool per process, created on first use, typed from the
// migrated schema (db-types.ts, generated by `pnpm db:migrate`). Nothing outside src/server/db imports pg or
// constructs Kysely (lint). The database skill (.claude/skills/database) has the rules for queries built on it.

/**
 * bigint (int8) arrives from node-postgres as a string, because it can exceed JavaScript's safe integers. Our
 * bigints are ids, counts and amounts far below 2^53 (an amount's CHECK keeps it under 10^15 tomans, ADR-0014), so
 * they become numbers, and a value that does not fit throws instead of silently losing precision. numeric stays a
 * string and is converted on purpose where it is used.
 */
export function parseInt8(text: string): number {
  const value = Number(text);
  if (!Number.isSafeInteger(value)) {
    throw new RangeError(`int8 value ${text} is outside JavaScript's safe integer range`);
  }
  return value;
}

const typeParsers: pg.CustomTypesConfig = {
  getTypeParser: (id, format) =>
    id === pg.types.builtins.INT8 ? parseInt8 : (pg.types.getTypeParser(id, format) as unknown),
};

const log = logger.child({ component: 'db' });

/** A statement slower than this is a warning in every environment: the query or its index needs a look. */
export const SLOW_QUERY_MS = 500;

/**
 * Every statement passes through here. A slow one is a warning; CARSHENAS_LOG_SQL=1 adds a debug line for each one,
 * with its parameters only in development, because parameters can hold personal data. A failed statement is only
 * debug: whether it is an error is the caller's decision, and a violated constraint is an expected result.
 */
export function logQuery(event: LogEvent): void {
  const { sql, parameters } = event.query;
  const durationMs = Math.round(event.queryDurationMillis * 10) / 10;
  const detail = { durationMs, sql, ...(env.isDevelopment && env.logSql && { parameters }) };
  if (event.level === 'error') {
    log.debug('statement failed', { ...detail, err: event.error });
  } else if (event.queryDurationMillis >= SLOW_QUERY_MS) {
    log.warn('slow statement', detail);
  } else if (env.logSql) {
    log.debug('statement', detail);
  }
}

function createDatabase(): Kysely<DB> {
  const pool = new pg.Pool({
    connectionString: env.databaseUrl,
    // A small VPS saturates at two to four busy connections per core; beyond that queries only queue inside
    // PostgreSQL. Measure pool waits (pool.waitingCount) before raising it: a starved pool usually means slow queries.
    max: 5,
    idleTimeoutMillis: 30_000,
    connectionTimeoutMillis: 5_000,
    // Names this process in pg_stat_activity and the server log. Timeouts are set on the role, not here.
    application_name: 'carshenas-web',
    types: typeParsers,
  });
  // An idle client can lose its connection (a database restart); unhandled, that error would crash the server.
  pool.on('error', (error) => {
    captureError(error, { message: 'idle database connection failed', fields: { component: 'db' } });
  });
  return new Kysely<DB>({ dialect: new PostgresDialect({ pool }), log: logQuery });
}

// Cached on globalThis so that hot reloading in development reuses the pool instead of opening a new one per edit.
const globalForDatabase = globalThis as typeof globalThis & { carshenasDatabase?: Kysely<DB> };

/** The database for writes: mutations and transactions (`database().transaction().execute(async (trx) => …)`). */
export function database(): Kysely<DB> {
  globalForDatabase.carshenasDatabase ??= createDatabase();
  return globalForDatabase.carshenasDatabase;
}

/** The same database typed read-only: `*-queries.ts` use this, so an insert there fails type-checking. */
export function readDatabase(): ReadonlyKysely<DB> {
  // ReadonlyKysely is a type-level view of the same instance; Kysely's own documentation converts with `as never`.
  return database() as unknown as ReadonlyKysely<DB>;
}
