import 'server-only';
import { Kysely, PostgresDialect, type LogEvent } from 'kysely';
import type { ReadonlyKysely } from 'kysely/readonly';
import pg from 'pg';
import type { DB } from '@/server/db/db-types';
import { env } from '@/server/env';

// The web app's only way into PostgreSQL (ADR-0012): one pool per process, created on first use, typed from the
// migrated schema (db-types.ts, generated by `pnpm db:migrate`). Nothing outside src/server/db imports pg or
// constructs Kysely (lint). The database skill (.claude/skills/database) has the rules for queries built on it.

/**
 * bigint (int8) arrives from node-postgres as a string, because it can exceed JavaScript's safe integers. Our
 * bigints are ids, counts and amounts far below 2^53, so they become numbers, and a value that does not fit throws
 * instead of silently losing precision. numeric stays a string and is converted on purpose where it is used.
 */
export function parseInt8(text: string): number {
  const value = Number(text);
  if (!Number.isSafeInteger(value)) {
    throw new RangeError(`int8 value ${text} is outside JavaScript's safe integer range`);
  }
  return value;
}

const typeParsers: pg.CustomTypesConfig = {
  getTypeParser: (id, format) =>
    id === pg.types.builtins.INT8 ? parseInt8 : (pg.types.getTypeParser(id, format) as unknown),
};

function logSql(event: LogEvent) {
  const { sql, parameters } = event.query;
  if (event.level === 'error') {
    console.error(`[sql] failed after ${event.queryDurationMillis.toFixed(1)} ms: ${sql}`, parameters);
  } else {
    console.info(`[sql] ${event.queryDurationMillis.toFixed(1)} ms: ${sql}`, parameters);
  }
}

function createDatabase(): Kysely<DB> {
  const pool = new pg.Pool({
    connectionString: env.databaseUrl,
    // A small VPS saturates at two to four busy connections per core; beyond that queries only queue inside
    // PostgreSQL. Measure pool waits (pool.waitingCount) before raising it: a starved pool usually means slow queries.
    max: 5,
    idleTimeoutMillis: 30_000,
    connectionTimeoutMillis: 5_000,
    // Names this process in pg_stat_activity and the server log. Timeouts are set on the role, not here.
    application_name: 'carshenas-web',
    types: typeParsers,
  });
  // An idle client can lose its connection (a database restart); unhandled, that error would crash the server.
  pool.on('error', (error) => {
    console.error('[db] an idle connection failed', error.message);
  });
  return new Kysely<DB>({
    dialect: new PostgresDialect({ pool }),
    log: env.isDevelopment && env.logSql ? logSql : undefined,
  });
}

// Cached on globalThis so that hot reloading in development reuses the pool instead of opening a new one per edit.
const globalForDatabase = globalThis as typeof globalThis & { carshenasDatabase?: Kysely<DB> };

/** The database for writes: mutations and transactions (`database().transaction().execute(async (trx) => …)`). */
export function database(): Kysely<DB> {
  globalForDatabase.carshenasDatabase ??= createDatabase();
  return globalForDatabase.carshenasDatabase;
}

/** The same database typed read-only: `*-queries.ts` use this, so an insert there fails type-checking. */
export function readDatabase(): ReadonlyKysely<DB> {
  // ReadonlyKysely is a type-level view of the same instance; Kysely's own documentation converts with `as never`.
  return database() as unknown as ReadonlyKysely<DB>;
}
