// The baseline: the violations that existed when the lint was introduced, as (file, rule, count), so that
// `pnpm copy:lint` fails only on a NEW violation or a worse count. The rewrite lanes (CS-106 to CS-110) lower it as they
// fix text: `pnpm copy:lint --update-baseline` only ever lowers a count or removes an entry. A count goes up in one case
// only: `--baseline-rule <id>` records the current violations of a rule that was just added or tightened.
import fs from 'node:fs';
import { compareText } from './sort.mjs';

const KEY_SEPARATOR = '\t';
export const keyOf = (file, rule) => `${file}${KEY_SEPARATOR}${rule}`;
export const splitKey = (key) => key.split(KEY_SEPARATOR);

export function loadBaseline(file) {
  const counts = new Map();
  if (!fs.existsSync(file)) return counts;
  const parsed = JSON.parse(fs.readFileSync(file, 'utf8'));
  for (const entry of parsed.entries ?? []) counts.set(keyOf(entry.file, entry.rule), entry.count);
  return counts;
}

/** Findings counted per (file, rule). */
export function countFindings(findings) {
  const counts = new Map();
  for (const finding of findings) {
    const key = keyOf(finding.file, finding.rule);
    counts.set(key, (counts.get(key) ?? 0) + 1);
  }
  return counts;
}

/** `worse`: more than the baseline allows (a new violation has baseline 0). `better`: fewer than the baseline records. */
export function compareToBaseline(current, baseline) {
  const worse = [];
  const better = [];
  for (const [key, count] of current) {
    const allowed = baseline.get(key) ?? 0;
    const [file, rule] = splitKey(key);
    if (count > allowed) worse.push({ file, rule, baseline: allowed, count });
  }
  for (const [key, allowed] of baseline) {
    const count = current.get(key) ?? 0;
    const [file, rule] = splitKey(key);
    if (count < allowed) better.push({ file, rule, baseline: allowed, count });
  }
  const order = (a, b) => compareText(a.file, b.file) || compareText(a.rule, b.rule);
  return { worse: worse.sort(order), better: better.sort(order) };
}

/**
 * The baseline after `--update-baseline` (`acceptRules` empty) or `--baseline-rule` (`acceptRules` named).
 * `ok` is false, and nothing should be written, when a count would rise outside an accepted rule.
 */
export function nextBaseline(current, baseline, acceptRules = new Set()) {
  const next = new Map();
  const refused = [];
  for (const [key, count] of current) {
    const [file, rule] = splitKey(key);
    if (acceptRules.has(rule)) {
      next.set(key, count);
      continue;
    }
    const allowed = baseline.get(key) ?? 0;
    if (count > allowed) refused.push({ file, rule, baseline: allowed, count });
    else next.set(key, count);
  }
  return { ok: refused.length === 0, next, refused };
}

/** One entry per line, sorted: a diff shows exactly the counts that moved, and a merge conflict is one line. */
export function serializeBaseline(counts) {
  const entries = [...counts]
    .map(([key, count]) => {
      const [file, rule] = splitKey(key);
      return { file, rule, count };
    })
    .sort((a, b) => compareText(a.file, b.file) || compareText(a.rule, b.rule));
  const lines = entries.map((entry) => `    ${JSON.stringify(entry)}`);
  return [
    '{',
    '  "version": 1,',
    '  "about": "Violations that existed when the copy lint was introduced (CS-105): the lint fails only on a new violation or a worse count. Generated by `pnpm copy:lint --update-baseline`, which only lowers it; see docs/runbooks/copy-lint.md.",',
    '  "entries": [',
    lines.join(',\n'),
    '  ]',
    '}',
    '',
  ].join('\n');
}

export function writeBaseline(file, counts) {
  fs.writeFileSync(file, serializeBaseline(counts));
}
