// The baseline: the violations that existed when the lint was introduced, as (file, rule, count), so that
// `pnpm copy:lint` fails only on a NEW violation or a worse count. The rewrite lanes (CS-106 to CS-110) lower it as they
// fix text: `pnpm copy:lint --update-baseline` only ever lowers a count or removes an entry. A count goes up in one case
// only: `--baseline-rule <id>` records the current violations of a rule that was just added or tightened.
//
// One file per rewrite area (tools/copy-lint/baseline/A.json ... E.json, CS-115.json): the areas have disjoint file lists, so
// five lanes lowering the baseline at once edit five different files and their merges never conflict.
import fs from 'node:fs';
import path from 'node:path';
import { compareText } from './sort.mjs';

const KEY_SEPARATOR = '\t';
export const keyOf = (file, rule) => `${file}${KEY_SEPARATOR}${rule}`;
export const splitKey = (key) => key.split(KEY_SEPARATOR);

/** Every `*.json` in the baseline folder, merged into one map from (file, rule) to count. */
export function loadBaseline(directory) {
  const counts = new Map();
  if (!fs.existsSync(directory)) return counts;
  for (const name of fs
    .readdirSync(directory)
    .filter((entry) => entry.endsWith('.json'))
    .sort()) {
    const parsed = JSON.parse(fs.readFileSync(path.join(directory, name), 'utf8'));
    for (const entry of parsed.entries ?? []) counts.set(keyOf(entry.file, entry.rule), entry.count);
  }
  return counts;
}

/** Findings counted per (file, rule). */
export function countFindings(findings) {
  const counts = new Map();
  for (const finding of findings) {
    const key = keyOf(finding.file, finding.rule);
    counts.set(key, (counts.get(key) ?? 0) + 1);
  }
  return counts;
}

/** `worse`: more than the baseline allows (a new violation has baseline 0). `better`: fewer than the baseline records. */
export function compareToBaseline(current, baseline) {
  const worse = [];
  const better = [];
  for (const [key, count] of current) {
    const allowed = baseline.get(key) ?? 0;
    const [file, rule] = splitKey(key);
    if (count > allowed) worse.push({ file, rule, baseline: allowed, count });
  }
  for (const [key, allowed] of baseline) {
    const count = current.get(key) ?? 0;
    const [file, rule] = splitKey(key);
    if (count < allowed) better.push({ file, rule, baseline: allowed, count });
  }
  const order = (a, b) => compareText(a.file, b.file) || compareText(a.rule, b.rule);
  return { worse: worse.sort(order), better: better.sort(order) };
}

/**
 * The baseline after `--update-baseline` (`acceptRules` empty) or `--baseline-rule` (`acceptRules` named).
 * `ok` is false, and nothing should be written, when a count would rise outside an accepted rule.
 */
export function nextBaseline(current, baseline, acceptRules = new Set()) {
  const next = new Map();
  const refused = [];
  for (const [key, count] of current) {
    const [file, rule] = splitKey(key);
    if (acceptRules.has(rule)) {
      next.set(key, count);
      continue;
    }
    const allowed = baseline.get(key) ?? 0;
    if (count > allowed) refused.push({ file, rule, baseline: allowed, count });
    else next.set(key, count);
  }
  return { ok: refused.length === 0, next, refused };
}

const ABOUT =
  'Violations of refuse rules that existed when the copy lint was introduced (CS-105): the lint fails only on a new violation or a worse count; warnings are never recorded. Generated by `pnpm copy:lint --update-baseline`, which only lowers it; see docs/runbooks/copy-lint.md.';

/** One entry per line, sorted: a diff shows exactly the counts that moved, and a merge conflict is one line. */
export function serializeBaseline(counts, area) {
  const entries = [...counts]
    .map(([key, count]) => {
      const [file, rule] = splitKey(key);
      return { file, rule, count };
    })
    .sort((a, b) => compareText(a.file, b.file) || compareText(a.rule, b.rule));
  const lines = entries.map((entry) => `    ${JSON.stringify(entry)}`);
  return [
    '{',
    '  "version": 1,',
    `  "area": ${JSON.stringify(area)},`,
    `  "about": ${JSON.stringify(ABOUT)},`,
    ...(lines.length === 0 ? ['  "entries": []'] : ['  "entries": [', lines.join(',\n'), '  ]']),
    '}',
    '',
  ].join('\n');
}

/** The counts split by the area each file belongs to: a Map from area id to its own counts (every area gets one). */
export function groupByArea(counts, areaOf, areaIds) {
  const groups = new Map(areaIds.map((id) => [id, new Map()]));
  for (const [key, count] of counts) {
    const area = areaOf(splitKey(key)[0]) ?? 'unassigned';
    if (!groups.has(area)) groups.set(area, new Map());
    groups.get(area).set(key, count);
  }
  return groups;
}

/** Writes one file per area into the folder (an area with nothing left keeps its file, with no entries). */
export function writeBaseline(directory, counts, areaOf, areaIds) {
  fs.mkdirSync(directory, { recursive: true });
  for (const [area, group] of groupByArea(counts, areaOf, areaIds)) {
    if (area === 'unassigned' && group.size === 0) continue;
    fs.writeFileSync(path.join(directory, `${area}.json`), serializeBaseline(group, area));
  }
}
