import { formatCount, formatCountOf } from '@carshenas/locale/format-number';

// Every word the listing page says (CS-64), in the glossary's terms (docs/product/glossary.md). What a deal band
// measures is never written here: it comes from the definitions in @carshenas/search and S01's numbers
// (gauge-view.ts), and what a rating rests on is written by listing-explanation.ts from stored facts. Tests import
// these constants instead of retyping Persian, which loses the zero-width non-joiner.

export const LISTING_COPY = {
  titleSuffix: 'قیمت و ارزیابی',
  /** The links under the title to the model's own page and to the rest of its listings (CS-67). */
  model: {
    label: 'مدل این خودرو',
    page: (name: string) => `صفحه‌ی مدل ${name}`,
    rest: 'بقیه‌ی آگهی‌های این مدل',
  },
  back: 'بازگشت به جست‌وجو',
  share: {
    label: 'اشتراک‌گذاری',
    copied: 'لینک کپی شد',
    failed: 'لینک کپی نشد. آن را از نوار آدرس بردارید.',
  },
  gallery: {
    label: 'عکس‌های آگهی',
    slide: (index: number, count: number) => `عکس ${formatCount(index)} از ${formatCount(count)}`,
    previous: 'عکس قبلی',
    next: 'عکس بعدی',
    thumbnails: 'عکس‌های کوچک آگهی',
    thumbnail: (index: number) => `رفتن به عکس ${formatCount(index)}`,
  },
  price: {
    negotiable: 'توافقی',
    unknown: 'قیمت نامشخص',
    installment: 'فروش قسطی',
    downPayment: 'پیش‌پرداخت',
    noFullPrice: 'قیمت کامل در آگهی نیامده',
    downPaymentNote: 'قیمت کامل خودرو در آگهی نیامده.',
    lastAsking: 'آخرین قیمت آگهی',
    asking: 'قیمت آگهی',
  },
  action: {
    openOn: (source: string) => `رفتن به آگهی در ${source}`,
    opensInNewTab: 'در زبانه‌ی جدید باز می‌شود',
    note: 'توضیحات کامل، گفت‌وگو با فروشنده و عکس‌های بیشتر را در آگهی اصلی می‌بینید.',
  },
  state: {
    off: (source: string) => `این آگهی دیگر روی ${source} نیست`,
    sold: 'این خودرو فروخته شده است',
    expired: 'مهلت این آگهی تمام شده است',
    offHint: 'قیمت و مشخصات زیر مربوط به پیش از آن تاریخ است.',
    since: (date: string) => `از ${date} دیده نشده است`,
    similarTitle: 'آگهی‌های مشابه روی بازار',
    similarHint: 'همین مدل، با سال ساخت و قیمتی نزدیک.',
    similarNone: 'آگهی مشابهی روی بازار نیست.',
    similarAll: 'دیدن همه‌ی آگهی‌های این مدل',
    seeSimilar: 'دیدن آگهی‌های مشابه',
    lastOnSource: (source: string) => `آخرین وضعیت آگهی در ${source}`,
  },
  analysis: {
    title: 'تحلیل قیمت',
    info: 'توضیح درباره‌ی ارزیابی قیمت',
    infoClose: 'بستن توضیح',
    thisPrice: 'قیمت این آگهی',
    marketValue: 'ارزش بازار',
    valuedOn: (date: string) => `برآورد ${date}`,
    beyondCheap: 'خیلی ارزان‌تر از مقیاس',
    beyondDear: 'خیلی گران‌تر از مقیاس',
    notValued: 'ارزش بازار هر روز حساب می‌شود.',
    why: 'چرا این ارزیابی؟',
    adjustments: 'ویژگی‌های اثرگذار',
    method: 'روش محاسبه',
  },
  comparables: {
    title: 'خودروهای مشابه',
    hint: 'آگهی‌هایی که سال و کارکردشان به این خودرو نزدیک است.',
    listLabel: 'خودروهای مشابه',
    asking: 'قیمت آگهی',
    adjusted: 'قیمت اگر مثل این خودرو بود',
    offMarket: 'از بازار رفته',
    showAll: (count: number) => `${formatCount(count)} آگهی دیگر`,
    none: 'آگهی مشابهی برای نمایش نیست. ارزش بازار از آگهی‌های همین مدل حساب شده است.',
  },
  history: {
    title: 'تاریخچه‌ی قیمت',
    listLabel: 'تغییرهای قیمت',
    daysOnMarket: 'روز روی بازار',
    totalChange: 'تغییر کل قیمت',
    noChange: 'قیمت از روز اول تغییر نکرده است',
    firstPriceUnknown: 'قیمت اول معلوم نیست',
    previousPrice: 'قیمت قبلی',
    published: 'آگهی منتشر شد',
    dropped: 'کاهش قیمت',
    raised: 'افزایش قیمت',
    priceSet: 'قیمت تعیین شد',
    lower: 'کمتر',
    higher: 'بیشتر',
    priceRemoved: 'قیمت از آگهی برداشته شد',
  },
  condition: {
    title: 'وضعیت خودرو',
    declaredTitle: 'گفته‌ی فروشنده',
    textTitle: 'خوانده‌شده از متن آگهی',
    textHint: 'زیر هر مورد، جمله‌ی آگهی آمده تا خودتان بسنجید.',
    none: 'در این آگهی از وضعیت خودرو چیزی نیامده است.',
    insurance: (months: number) => `بیمه‌ی شخص ثالث: ${formatCountOf(months, 'ماه')} باقی‌مانده`,
  },
  risks: {
    title: 'نکته‌های احتیاطی',
    listLabel: 'نکته‌های احتیاطی',
  },
  facts: {
    title: 'مشخصات',
    year: 'سال ساخت',
    mileage: 'کارکرد',
    gearbox: 'گیربکس',
    fuel: 'سوخت',
    engineVolume: 'حجم موتور',
    engineVolumeFrom: { listing: 'طبق عنوان آگهی', trim: 'طبق مشخصات تیپ', model: 'تقریبی، طبق مدل' },
    origin: 'مبدأ',
    country: 'کشور سازنده',
    colour: 'رنگ',
    city: 'محل',
    seller: 'فروشنده',
    source: 'منبع',
    listed: 'تاریخ انتشار',
    daysOnMarket: 'روی بازار',
    zeroKm: 'صفر کیلومتر',
  },
  freshness: {
    checked: (ago: string) => `آخرین بررسی: ${ago}`,
    seen: (ago: string) => `آخرین بار دیده شد: ${ago}`,
    requesting: 'در حال ثبت درخواست بررسی…',
    queued: 'درخواست بررسی ثبت شد',
    queuedHint: 'بعد از بررسی، اطلاعات این صفحه به‌روز می‌شود.',
    failed: 'درخواست بررسی ثبت نشد.',
    busy: 'درخواست‌های بررسی زیاد است. کمی بعد دوباره سر بزنید.',
  },
  states: {
    notFoundTitle: 'این آگهی پیدا نشد',
    notFoundBody: 'شاید نشانی را اشتباه وارد کرده‌اید یا آگهی برداشته شده است.',
    backToSearch: 'رفتن به جست‌وجو',
  },
} as const;
