import { formatCount, formatCountOf } from '@carshenas/locale/format-number';
import { FRESHNESS_WINDOW_HOURS } from '@/features/listing/listing-rules';

// Every word the listing page says (CS-64), in the glossary's terms (docs/product/glossary.md). What a deal band
// measures is never written here: it comes from the definitions in @carshenas/search and S01's numbers
// (gauge-view.ts), and what a rating rests on is written by listing-explanation.ts from stored facts. Tests import
// these constants instead of retyping Persian, which loses the zero-width non-joiner.

export const LISTING_COPY = {
  titleSuffix: 'قیمت و ارزیابی',
  /** The links under the title to the model's own page and to the rest of its listings (CS-67). */
  model: {
    label: 'مدل این خودرو',
    page: (name: string) => `صفحه‌ی ${name}: قیمت و روند`,
    rest: 'بقیه‌ی آگهی‌های این مدل',
  },
  back: 'بازگشت به جست‌وجو',
  share: {
    label: 'اشتراک‌گذاری',
    copy: 'کپی پیوند',
    copied: 'پیوند کپی شد',
    failed: 'پیوند کپی نشد؛ آن را از نوار آدرس بردارید.',
  },
  gallery: {
    label: 'عکس‌های آگهی',
    slide: (index: number, count: number) => `عکس ${formatCount(index)} از ${formatCount(count)}`,
    previous: 'عکس قبلی',
    next: 'عکس بعدی',
    thumbnails: 'عکس‌های کوچک آگهی',
    thumbnail: (index: number) => `رفتن به عکس ${formatCount(index)}`,
    none: 'این آگهی عکس ندارد',
    fromSource: (source: string) => `عکس‌ها از ${source}`,
  },
  price: {
    negotiable: 'توافقی',
    unknown: 'قیمت نامشخص',
    installment: 'فروش قسطی',
    downPayment: 'پیش‌پرداخت',
    noFullPrice: 'قیمت کامل در آگهی نیامده',
    downPaymentNote: 'قیمت خودرو در آگهی نیامده؛ مبلغ بالا فقط پیش‌پرداخت است.',
    lastAsking: 'آخرین قیمت آگهی',
    asking: 'قیمت آگهی',
  },
  action: {
    openOn: (source: string) => `دیدن آگهی در ${source}`,
    opensInNewTab: 'در زبانه‌ی جدید باز می‌شود',
    note: 'برای دیدن توضیحات کامل، گفت‌وگو با فروشنده و عکس‌های بیشتر، به آگهی در منبع بروید.',
  },
  state: {
    off: (source: string) => `این آگهی دیگر روی ${source} نیست`,
    sold: 'این خودرو فروخته شده است',
    expired: 'مهلت این آگهی تمام شده است',
    gone: 'این آگهی از منبع برداشته شده است',
    offHint: 'قیمت و مشخصات زیر آخرین چیزی است که از آگهی دیده‌ایم. بدون ارزیابی تازه، به آن‌ها تکیه نکنید.',
    since: (date: string) => `از ${date}`,
    similarTitle: 'آگهی‌های مشابهی که هنوز روی بازارند',
    similarHint: 'همین مدل، با سال ساخت و قیمتی نزدیک.',
    similarNone: 'آگهی مشابه فعالی پیدا نکردیم.',
    similarAll: 'دیدن همه‌ی آگهی‌های این مدل',
    seeSimilar: 'دیدن آگهی‌های مشابه',
    lastOnSource: (source: string) => `آخرین وضعیت آگهی در ${source}`,
  },
  analysis: {
    title: 'تحلیل قیمت',
    sectionLabel: 'تحلیل قیمت این آگهی',
    gaugeLabel: 'جایگاه قیمت آگهی روی ارزش بازار',
    info: 'توضیح درباره‌ی ارزیابی قیمت',
    infoClose: 'بستن توضیح',
    thisPrice: 'قیمت این آگهی',
    marketValue: 'ارزش بازار',
    valuedOn: (date: string) => `برآورد ${date}`,
    beyondCheap: 'خیلی ارزان‌تر از مقیاس',
    beyondDear: 'خیلی گران‌تر از مقیاس',
    unratedTitle: 'قیمت این آگهی ارزیابی نشده',
    noValueTitle: 'برای این آگهی ارزش بازاری نداریم',
    notValued: 'ارزش بازار هر روز برای آگهی‌های خوانده‌شده حساب می‌شود؛ این آگهی هنوز در آن نیست.',
    why: 'چرا این ارزیابی؟',
    adjustments: 'تعدیل‌ها',
    method: 'روش محاسبه',
    markerNote: 'جای قیمت این آگهی روی مقیاس، نسبت به ارزش بازار',
    underBar: (rating: string) => `ارزیابی: ${rating}`,
    gapOnScale: 'فاصله با ارزش بازار روی مقیاس',
  },
  comparables: {
    title: 'آگهی‌های مشابهی که ارزش بازار از آن‌ها حساب شد',
    hint: 'نزدیک‌ترین آگهی‌ها به این خودرو در سال ساخت و کارکرد. «قیمت برای این خودرو» قیمت هر کدام است اگر مثل این خودرو بود.',
    listLabel: 'آگهی‌های مشابه',
    asking: 'قیمت آگهی',
    adjusted: 'قیمت برای این خودرو',
    offMarket: 'از بازار رفته',
    showAll: (count: number) => `نمایش همه‌ی ${formatCount(count)} آگهی`,
    none: 'آگهی مشابهی برای نمایش نداریم؛ ارزش بازار از کل آگهی‌های این مدل حساب شده است.',
  },
  history: {
    title: 'تاریخچه‌ی قیمت',
    listLabel: 'تغییرهای قیمت',
    daysOnMarket: 'روز روی بازار',
    totalChange: 'تغییر کل قیمت',
    noChange: 'قیمت از روز اول تغییر نکرده است',
    firstPriceUnknown: 'قیمت اولیه ثبت نشده',
    previousPrice: 'قیمت قبلی',
    published: 'آگهی منتشر شد',
    dropped: 'کاهش قیمت',
    raised: 'افزایش قیمت',
    priceSet: 'قیمت تعیین شد',
    lower: 'کمتر',
    higher: 'بیشتر',
    priceRemoved: 'قیمت از آگهی برداشته شد',
    firstSeen: (date: string) => `آگهی ${date} منتشر شد`,
  },
  condition: {
    title: 'وضعیت خودرو',
    declaredTitle: 'اعلام‌شده توسط فروشنده',
    textTitle: 'خوانده‌شده از متن آگهی',
    textHint:
      'جمله‌ی کوتاهی که هر مورد از آن خوانده شد زیر آن آمده است؛ اگر اشتباه است، به آگهی در منبع تکیه کنید.',
    quote: 'جمله‌ی آگهی',
    none: 'فروشنده وضعیتی اعلام نکرده و متن آگهی هم چیزی نگفته است.',
    declaredNone: 'چیزی اعلام نشده',
    insurance: (months: number) => `بیمه‌ی شخص ثالث: ${formatCountOf(months, 'ماه')} باقی‌مانده`,
  },
  risks: {
    title: 'نکته‌های احتیاط',
    listLabel: 'نکته‌های احتیاط',
    none: 'نکته‌ی احتیاطی ندیدیم.',
  },
  facts: {
    title: 'مشخصات',
    year: 'سال ساخت',
    mileage: 'کارکرد',
    gearbox: 'گیربکس',
    fuel: 'سوخت',
    colour: 'رنگ',
    city: 'محل',
    seller: 'فروشنده',
    source: 'منبع',
    listed: 'تاریخ انتشار',
    daysOnMarket: 'روی بازار',
    zeroKm: 'صفر کیلومتر',
  },
  freshness: {
    title: 'تازگی اطلاعات',
    checked: (ago: string) => `آخرین بررسی: ${ago}`,
    neverChecked: 'صفحه‌ی این آگهی هنوز بررسی نشده است',
    seen: (ago: string) => `آخرین بار در فهرست منبع: ${ago}`,
    stale: `اطلاعات این آگهی بیش از ${formatCountOf(FRESHNESS_WINDOW_HOURS, 'ساعت')} پیش خوانده شده است.`,
    requesting: 'در حال ثبت درخواست بررسی مجدد…',
    queued: 'بررسی مجدد در صف است',
    queuedHint: 'درخواست شما ثبت شد؛ هر وقت صفحه‌ی آگهی دوباره خوانده شود، اطلاعات این صفحه به‌روز می‌شود.',
    failed: 'درخواست بررسی مجدد ثبت نشد.',
    busy: 'صف بررسی مجدد فعلاً پر است؛ کمی بعد دوباره سر بزنید.',
    retry: 'دوباره درخواست کنید',
    fresh: 'اطلاعات این آگهی تازه است.',
  },
  states: {
    notFoundTitle: 'این آگهی پیدا نشد',
    notFoundBody: 'شاید نشانی را اشتباه وارد کرده‌اید یا آگهی از کارشناس حذف شده است.',
    backToSearch: 'رفتن به جست‌وجو',
  },
} as const;
