import type { BodyTypeCode } from './codes.ts';

// Divar's own make and model lists (CS-50 criterion 3): the brand_model filter values its search takes, read in the
// measurement of 2026-09-29 (CS-33: 807 models, docs/research/2026-09-28-listing-data-and-freshness/) and the make
// values its whole market's first page names (161 makes, from the crawl's job history of 2026-09-30). A model's key
// is its make's key, a space, and the rest («Peugeot 206»); its trims («Peugeot 206 5») are learned from the posts and
// list rows that name them. Body types are curated by hand for every model that had Tehran listings (the owner's
// decision of 2026-09-30), from knowledge of the Iranian market; a model without listings stays null, unclassified,
// and CURATION_DOUBTS names the ones to check. A make's Persian name is curated where certain, else null until named.

const ZWNJ = String.fromCodePoint(0x200c);

type Models = Readonly<Record<string, BodyTypeCode | null>>;
export type DivarMake = { readonly nameFa: string | null; readonly models: Models };

const s = 'sedan';
const h = 'hatchback';
const x = 'crossover';
const u = 'suv';
const p = 'pickup';
const v = 'van';
const m = 'minivan';
const c = 'coupe';
const k = 'convertible';
const w = 'wagon';

/** By Divar's make key; each model by the rest of its key. */
export const DIVAR_MAKES: Readonly<Record<string, DivarMake>> = {
  'Alfa Romeo': { nameFa: 'آلفارومئو', models: { Giulietta: h, MiTo: h, '4C': c } },
  Amg: { nameFa: null, models: { Tooca: x, Arka: null, Artan: null } },
  Amico: { nameFa: 'امیکو', models: { Asna: p, Araz: null } },
  Ario: { nameFa: 'آریو', models: { 'automatic-1600cc': s, 'manual-1600cc': s, 'manual-1500cc': s } },
  Arisan: { nameFa: 'آریسان', models: { 'Arisun 2': p, Arisan: p } },
  Audi: {
    nameFa: 'آئودی',
    models: {
      'Q5 e-tron': x,
      'Q4 e-tron': x,
      'Q5-normal': x,
      'A3 Sedan': s,
      E7X: x,
      TT: c,
      A4: s,
      'A3L 1.5L Turbo': null,
    },
  },
  Avatr: { nameFa: 'آواتر', models: { '11': x, '07 Erev': x, '12 Ultra Erev': s } },
  BAC: { nameFa: null, models: { 'X3 PRO': x } },
  BAIC: {
    nameFa: 'بایک',
    models: {
      'U5 PLUS': s,
      'Beijing X7': x,
      Sabrina: h,
      BJ30e: x,
      X25: x,
      'Beijing X55': x,
      'Sabrina-ir': h,
      Senova: s,
      BJ40: u,
      EU5: null,
    },
  },
  BAW: { nameFa: 'باو', models: { '212': u } },
  Bestune: { nameFa: 'بستیون', models: { Nat: x, T77: x, T99: null } },
  Besturn: { nameFa: 'بسترن', models: { B30: s, B50: s, B50F: s } },
  BMW: {
    nameFa: `بی${ZWNJ}ام${ZWNJ}و`,
    models: {
      '5 Series Sedan': s,
      X3: x,
      '3 Series Sedan': s,
      X4: x,
      '2 Series Grancoupe': s,
      '7 Series': s,
      '225i': m,
      X2: x,
      iX1: x,
      X1: x,
      '3 Series Convertible': k,
      iX3: x,
      '4 Series Convertible': k,
      '6 Series Convertible': k,
      X6: u,
      Z4: k,
      '1 Series Hatchback': h,
      '4 Series Grancoupe': s,
      '4 Series Coupe': c,
      '6 Series Coupe': c,
      '1 Series Convertible': k,
      '2 Series Activetourer': m,
      '3 Series Coupe': c,
      i5: s,
      Classic: s,
      '2 Series Coupe': c,
      '2002': s,
      '3 Series GT': h,
      X5: u,
      i8: c,
      '1 Series Coupe': c,
      '2 Series Convertible': k,
      '218i Grand Coupe': s,
      '6 Series Grancoupe': s,
      '116i': null,
      '220i Grand Coupe': null,
      '318i': null,
      '5 Series GT': null,
      Z3: null,
    },
  },
  Brilliance: {
    nameFa: 'برلیانس',
    models: { H320: h, H330: s, H230: s, H220: h, C3: x, Van: v, V5: x, V6: null },
  },
  BYD: {
    nameFa: `بی${ZWNJ}وای${ZWNJ}دی`,
    models: {
      'SONG PLUS': x,
      'SEALION 06 DMi': x,
      'Qin Plus': s,
      'Qin-L': s,
      'Destroyer 05 DMi': s,
      S6: x,
      'SEAL 06 DMi': s,
      Dolphin: h,
      HAN: s,
      F3: null,
      S7: null,
      'SEAL 05 DMi': null,
      Seagull: null,
    },
  },
  Capra: {
    nameFa: 'کاپرا',
    models: {
      'Double Cabin': p,
      'B-normal': p,
      'U double cabin 2.4L AT': p,
      'Single-cabin': p,
      'Capra 2': p,
      'U-normal': p,
      'B Double-cabin': null,
    },
  },
  Changan: {
    nameFa: 'چانگان',
    models: {
      'CS 55': x,
      'Uni-T': x,
      'CS35-ir': x,
      'CS35-normal': x,
      'CS 35  3': x,
      'EADO EV460': s,
      'EADO-normal': s,
      'NEVO A05': s,
      'Cs 35 2': x,
      'Hunter Plus pick-up': p,
      'X5 Plus': x,
    },
  },
  Chery: {
    nameFa: 'چری',
    models: {
      'Arrizo 5': s,
      'Tiggo 5': x,
      'Tiggo 7': x,
      'Arizo 5 sport FL': s,
      'Arrizo 5IE New': s,
      'Arrizo 6': s,
      'Arrizo 5TE': s,
      Queen: h,
      'Viana A15': s,
    },
  },
  Cheval: { nameFa: null, models: { '6 HEV 1.5L Turbo': x } },
  Citroen: {
    nameFa: 'سیتروئن',
    models: { Xantia: s, C3: h, C5: s, 'New C5': s, Jian: x, Sialk: null, Xantia2: null },
  },
  Daewoo: { nameFa: 'دوو', models: { Cielo: s, Matiz: h, Racer: s, Espero: s } },
  Dayun: { nameFa: 'دایون', models: { Y7: x, 'Y5-normal': x, 'Y5 Plus': x, DX: null } },
  Delica: { nameFa: 'دلیکا', models: { Van: v } },
  Dena: { nameFa: 'دنا', models: { plus: s, basic: s } },
  Dignity: { nameFa: 'دیگنیتی', models: { Prime: x, Prestige: x } },
  Dongfeng: {
    nameFa: `دانگ${ZWNJ}فنگ`,
    models: {
      H30: h,
      E70: s,
      'Shine Max-normal': s,
      S30: s,
      'Shine Max Hybrid': s,
      E5: null,
    },
  },
  DS: {
    nameFa: `دی${ZWNJ}اس`,
    models: { '6': x, '5-normal': h, '5LS': s, 'crossback-7': x, '3': h, 'Crossback-4': null },
  },
  Envoy: { nameFa: null, models: { HEV: x } },
  Eres: { nameFa: null, models: { hm5: x, m7: null } },
  Farda: {
    nameFa: 'فردا',
    models: {
      '511': p,
      Sx5: x,
      'T5-normal': x,
      'm4 Suba': m,
      'T5 Plus': x,
      'SX5 PLUS': x,
      Sx6: x,
      'Suba M4': null,
    },
  },
  Fiat: {
    nameFa: 'فیات',
    models: {
      '500': h,
      Siena: s,
      R500: h,
      '500x': null,
      'TIPO CROSS 1600': null,
      'TIPO SEDAN 1600': null,
    },
  },
  Fidelity: {
    nameFa: 'فیدلیتی',
    models: {
      Elite: x,
      'Prestige 7 seater': x,
      Prime: x,
      'FIDELITY PRESTIGE': x,
      XB1: null,
    },
  },
  Foton: { nameFa: 'فوتون', models: { 'Tunland G7': p, Pickup: p, Van: v, Sauvana: u } },
  Fownix: {
    nameFa: 'فونیکس',
    models: {
      'ARIZO 6 GT': s,
      'ARIZO 8': s,
      'Arrizo 6 pro': s,
      Fx: x,
      'Tiggo 7 pro Max 1.6L Turbo awd': x,
      'Tiggo 7 pro Premium': x,
      'Tiggo 8 pro Max IE': x,
      'FX EV': x,
      'Tiggo 7 pro E plus Plugin hybrid': x,
      'Tiggo 8 Promax': x,
      'Tiggo 7 pro-normal': x,
      'Tiggo 8 pro Max E plus Plugin hybrid': x,
      'Tiggo 8 pro-normal': x,
      'تیگو 8 پرو E plus': x,
      'Tiggo 7 pro Max-normal': x,
      'Tiggo 9': u,
    },
  },
  Gac: {
    nameFa: `جی${ZWNJ}ای${ZWNJ}سی`,
    models: {
      Es9: u,
      GS3: x,
      EMKOO: x,
      'Empow Hybrid': s,
      EMPOW: s,
      'Emkoo Hybrid': x,
      GS8: u,
      'E9 Plugin Hybrid 2.0L Turbo': m,
      Trumpchi: s,
    },
  },
  Geely: {
    nameFa: 'جیلی',
    models: {
      'Emgrand 7': s,
      GC6: s,
      'Emgrand X7': x,
      AZKARRA: x,
      'Emgrand 7_RV': h,
      'GX3 PRO': x,
      BINRUI: null,
      'COOLRAY PLUS': null,
      'GEOMETRY C': null,
      MONJARO: null,
      PREFACE: null,
    },
  },
  'Great-Wall': {
    nameFa: `گریت${ZWNJ}وال`,
    models: {
      Tank: u,
      C30: s,
      'Pickup Wingle 5-double cabin': p,
      'Pickup Wingle 3': p,
      'Pickup Wingle 5-single cabin': p,
      Van: null,
    },
  },
  Haima: { nameFa: 'هایما', models: { S5: x, S7: x, S8: x, X7: m } },
  Haval: {
    nameFa: 'هاوال',
    models: {
      H9: u,
      'H6 HEV': x,
      'H2-ir': x,
      'H6-normal': x,
      'M4-normal': x,
      'H6-ir': x,
      H8: u,
      'M4-ir': null,
    },
  },
  Honda: {
    nameFa: 'هوندا',
    models: {
      'HR-V-normal': x,
      Accord: s,
      ENS1: x,
      Civic: s,
      'HR-V eHEV': x,
      VEZEL: x,
      'CR-V': x,
      City: s,
      'ZR-V Hybrid': x,
      'CR-X': null,
      Legend: null,
    },
  },
  Hongqi: { nameFa: 'هونگچی', models: { H5: s, 'E-QM5': s } },
  Hyundai: {
    nameFa: 'هیوندای',
    models: {
      'Azera Grandeur': s,
      'Santafe ix45': u,
      'Tucson-ix35': x,
      Elantra: s,
      'Sonata-NF': s,
      'Sonata-YF': s,
      Accent: s,
      'Veracruz-ix55': u,
      Verna: s,
      Genesis: s,
      'Hyundai Elantra 1600': s,
      'Sonata-LF-hybrid': s,
      Avante: s,
      'Hyundai Hyundai Elantra 1800': s,
      Veloster: h,
      'i20-normal': h,
      'Sonata 1.5L Turbo': s,
      'Accent-ir': s,
      i30: h,
      Kona: x,
      'i20-ir': h,
      'Sonata-LF-normal': s,
      'Tucson 1.5L Turbo': x,
      'FX Coupe': c,
      'i10-ir': h,
      'hyundai creta': x,
      Centennial: s,
      Van: v,
      Palisade: u,
      Excel: s,
      'i40-normal': s,
      'Elantra-ir': s,
      Trajet: m,
      'i40 Station': w,
      Scoupe: null,
    },
  },
  inroads: { nameFa: null, models: { 'Van C35': v } },
  'Iran Khodro': {
    nameFa: `ایران${ZWNJ}خودرو`,
    models: { 'RIRA 1.7L Turbo': s, 'LUNA GRE EV': s, 'RIRA EV': s },
  },
  'IranKhodro Van': { nameFa: `ایران${ZWNJ}خودرو ون`, models: { Ghazal: v, Vana: v } },
  JAC: {
    nameFa: 'جک',
    models: {
      J4: s,
      S5: x,
      S3: x,
      J5: s,
      'J3 Hatchback': h,
      'J3 Sedan': s,
      Van: v,
    },
  },
  Jeep: {
    nameFa: 'جیپ',
    models: {
      Sahra: u,
      KM: u,
      Shahbaz: u,
      Ahoo: u,
      Pickup: p,
      Cherokee: null,
      Mute: null,
      Renegade: null,
      Wagoneer: null,
      Wrangler: null,
    },
  },
  Kia: {
    nameFa: 'کیا',
    models: {
      Cerato: s,
      Optima: s,
      Rio: s,
      'Rio-ir': s,
      Sportage: x,
      'Cerato-ir': s,
      Sorento: u,
      'K5 TURBO': s,
      'K3-normal': s,
      mohave: u,
      Picanto: h,
      Opirus: s,
      cadenza: s,
      EV5: x,
      carens: m,
      'K5-normal': s,
      'Seltos Turbo': x,
      carnival: m,
      'K3 GT line': s,
      Stonic: x,
      'Optima-hybrid': s,
      'Seltos 1.5L': x,
      Sonet: x,
      Van: v,
      'Seltos-normal': x,
      "Cee'd": null,
      K8: null,
      Pegas: null,
      'Q3 Sportback': null,
      soul: null,
    },
  },
  KMC: {
    nameFa: `کی${ZWNJ}ام${ZWNJ}سی`,
    models: {
      Eagle: x,
      J7: s,
      T8: p,
      'T9 pick-up': p,
      X5: x,
      SR3: x,
      K7: x,
      A5: s,
      'SR6 1.5L Turbo': x,
      'EJ7-normal': s,
      'EJ7 PLUS': s,
      JS6: x,
    },
  },
  Lamari: {
    nameFa: 'لاماری',
    models: {
      'ECHO 1.5 Turbo': x,
      'Eama-normal': x,
      'NEO 1.5 Turbo': x,
      'Eama HEV Hybrid': x,
      'HIRCANI 1.6 Turbo': null,
    },
  },
  'Land Rover': {
    nameFa: 'لندروور',
    models: {
      'Range Rover-Evoque': x,
      'Range Rover-normal': u,
      Defender: u,
      ir: u,
      Discovery: u,
      Freelander: null,
    },
  },
  Lexus: {
    nameFa: 'لکسوس',
    models: {
      RX: x,
      LX: u,
      'NX 300 H': x,
      ES: s,
      IS: s,
      'NX 200t': x,
      'NX 350': x,
      GS: s,
      CT: h,
      LS: s,
    },
  },
  Lifan: { nameFa: 'لیفان', models: { X60: x, X50: x, '620': s, '820': s, '520': s, X70: x, '520i': h } },
  LUCANO: { nameFa: 'لوکانو', models: { L7: x, L8: x } },
  Maxmotor: {
    nameFa: null,
    models: { Kalut: p, 'Tiara-normal': s, 'Tiam 1.5L': x, 'Tiara prime': s },
  },
  Mazda: {
    nameFa: 'مزدا',
    models: {
      '3': s,
      '3-ir': s,
      '3N Sedan-ir': s,
      Pickup: p,
      '323': s,
      'EZ6 Hybrid EREV': s,
      EZ60: x,
      'EZ6-normal': s,
      'CX-30': x,
      '2-ir': h,
      '3N Hatchback-ir': h,
      'CX-50-normal': x,
      '6-normal': s,
      '626': null,
      'CX-50 Hybrid': null,
      CX5: null,
      CX9: null,
    },
  },
  'Mercedes-Benz': {
    nameFa: 'مرسدس بنز',
    models: {
      'C Class': s,
      'E Class': s,
      'A Class': h,
      'S Class': s,
      'EQE 500 SUV': u,
      'CLS Class': s,
      'EQB 260': x,
      'SL Class': k,
      Van: v,
      'G Class': u,
      Classic: s,
      'GLE Class': u,
      'EQA 260': x,
      'GLB Class': x,
      'GLC Class': x,
      'CLA Class': s,
      'GLA Class': x,
      'ML Class': u,
      A180: h,
      'CLK Class convertible': k,
      'B Class': m,
      'CL Class': c,
      'E Class-ir': s,
      'GL Class': u,
      'GLS Class': u,
      GTS: c,
      'AMG EQE SUV': u,
      'GLK Class': x,
      'SLK Class': k,
      'CE Class': null,
      'CLA 180': null,
      'CLK Class Coupe': null,
      'GLB 180': null,
      'GLB 200': null,
      'SLC Class': null,
      'SLR Class': null,
      'SLS Class': null,
      Unimog: null,
      Viano: null,
    },
  },
  MG: {
    nameFa: `ام${ZWNJ}جی`,
    models: {
      GT: s,
      '6': s,
      '550': s,
      '3-normal': h,
      'MG 5': s,
      GS: x,
      '360': s,
      ZS: x,
      '4 EV XPOWER': h,
      '350': s,
      RX5: x,
      Cyberster: null,
      'MG 7': null,
      'Roewe D7': null,
      TORRES: null,
    },
  },
  Mitsubishi: {
    nameFa: 'میتسوبیشی',
    models: {
      Outlander: x,
      'Eclipse Cross': x,
      Lancer: s,
      'Pajero 4 door': u,
      Galant: s,
      ASX: x,
      Mirage: h,
      'Pajero 2 door': u,
      'Pajero-ir': u,
      Pickup: p,
      Van: v,
    },
  },
  MVM: {
    nameFa: `ام${ZWNJ}وی${ZWNJ}ام`,
    models: {
      '110': h,
      '315 hatchback': h,
      X22: x,
      X22pro: x,
      X33: x,
      X55: x,
      X77: x,
      'Arizo 5 sport FL': s,
      X33S: x,
      '530': s,
      '110S': h,
      '550': s,
      '315 Sedan': s,
      '315 Hatchback Plus': h,
      'Arrizo 5ev': s,
      'M5 Pro': s,
    },
  },
  Narvan: { nameFa: null, models: { Taxi: v, Personal: v } },
  Nissan: {
    nameFa: 'نیسان',
    models: {
      'Maxima-ir': s,
      Qashqai: x,
      'Sylphy E power': s,
      'Patrol 4 door': u,
      'Patrol 2 door': u,
      Terra: u,
      Pickup: p,
      Juke: x,
      Altima: s,
      Roniz: p,
      'Terra Exclusive': u,
      Murano: x,
      'Maxima-im': s,
      'N6 PHEV': s,
      'X-Trail': x,
      'Teana-ir': s,
      'Sylphy Enjoy Edition': s,
      Navara: p,
      'Sylphy-normal': s,
      'Qashqai-ir': x,
      Seranza: s,
      'Terra Leo mx8 2.0L Turbo': u,
      Pathfinder: u,
      'Teana-im': s,
      'X-Terra': u,
      NX8: x,
      Sunny: s,
      'X trail': x,
      Magnite: x,
      Armada: u,
      'KICKS 1.6L': x,
      N7: s,
      'KICKS-normal': x,
      'Terra Pickup': p,
      'Sylphy Joyful': s,
      Tiida: null,
    },
  },
  Opel: {
    nameFa: 'اوپل',
    models: {
      Corsa: h,
      Astra: h,
      Mokka: x,
      'Mokka 1.2L Turbo': x,
      Vectra: s,
      Omega: s,
      'CROSS LAND': null,
      Calibra: null,
      Insignia: null,
    },
  },
  'PARS KHODRO': { nameFa: `پارس${ZWNJ}خودرو`, models: { NOA: x, P90: s } },
  Paykan: { nameFa: 'پیکان', models: { Pickup: p, Petrol: s, 'Bi-fuel(CNG)': s, 'Bi-fuel(LPG)': s } },
  Pazhan: { nameFa: 'پاژن', models: { '4 door': u, '2 door': u, Herour: u } },
  Peugeot: {
    nameFa: 'پژو',
    models: {
      '206': h,
      '207i': h,
      '405': s,
      Pars: s,
      '2008': x,
      Roa: s,
      RD: s,
      RDI: s,
      '407': s,
      '508': s,
      '504': s,
      '301': s,
      '205': h,
      '307': h,
      '204': null,
      '304': null,
      '306': null,
      '308': null,
      '403': null,
      '404': null,
      '406': null,
      '505': null,
      '605': null,
      '607': null,
      '806': null,
      Limousine: null,
      Partner: null,
      RCZ: null,
    },
  },
  Porsche: {
    nameFa: 'پورشه',
    models: { Cayenne: u, Panamera: s, Macan: x, Boxster: k, '911': c, Cayman: null },
  },
  Pride: {
    nameFa: 'پراید',
    models: {
      '111': h,
      '131': s,
      Pickup: p,
      'Saba GLXI': s,
      Sedan: s,
      '141': h,
      '132': s,
      Hatchback: h,
      Automatic: s,
      Station: w,
    },
  },
  Proton: { nameFa: 'پروتون', models: { 'Gen-2': h, Viera: s, Impian: s } },
  Quick: {
    nameFa: 'کوییک',
    models: { GXR: h, RS: h, manual: h, GX: h, Automatic: h, GXH: h },
  },
  Rayen: { nameFa: null, models: { V5: x, R3: x } },
  Reera: { nameFa: null, models: { '1.7L Turbo 6 At': x, EV: null } },
  Renault: {
    nameFa: 'رنو',
    models: {
      Megan: s,
      Sandero: h,
      'Tondar 90': s,
      Koleos: x,
      'Sandero-Stepway': h,
      'Megan-ir': s,
      Talisman: s,
      'Pars Tondar': s,
      Captur: x,
      Fluence: s,
      Duster: x,
      PK: s,
      Pickup: p,
      Symbol: s,
      Scala: s,
      Safrane: s,
      '5-normal': h,
      'Arkana XM3': x,
      Latitude: s,
      '21': s,
      '5-ir': h,
      Sepand: p,
      '9 GTL': null,
      Clio: null,
      Laguna: null,
      Modus: null,
      Van: null,
    },
  },
  Respect: { nameFa: 'ریسپکت', models: { 'RESPECT II': x, Prime: x } },
  Roewe: { nameFa: 'روئو', models: { 'eRX5 Hybrid': x } },
  Runna: {
    nameFa: 'رانا',
    models: { 'Plus TU5P': s, 'Plus-normal': s, LX: s, 'Plus P': s, EL: s },
  },
  Saina: {
    nameFa: 'ساینا',
    models: { manual: s, GX: s, 'GXL CNG': s, automatic: s, 'GXL-normal': s, S: s },
  },
  Saipa: {
    nameFa: 'سایپا',
    models: {
      'Atlas G': h,
      Sahand: s,
      'Atlas GL': h,
      'Atlas S': h,
      'Karvan Saipa': m,
      'Atlas E Plus': h,
      '421P': p,
      '441P': p,
      Arya: s,
      'Atlas E-normal': h,
      'Atlas L': null,
    },
  },
  Samand: { nameFa: 'سمند', models: { LX: s, Soren: s, X7: s, SE: s, EL: s, Sarir: s } },
  Shahin: { nameFa: 'شاهین', models: { 'G-normal': s, Plus: s, GL: s, 'G CVT': s } },
  SsangYong: {
    nameFa: `سانگ${ZWNJ}یانگ`,
    models: {
      Tivoli: x,
      Musso: p,
      'Tivoli-IR': x,
      Korando: x,
      Rexton: u,
      Actyon: u,
      'new actyon': x,
      'new-korando': x,
      Kyron: u,
      'Rexton-ir': u,
      Rodius: m,
      Chairman: s,
      Khan: p,
    },
  },
  Suzuki: {
    nameFa: 'سوزوکی',
    models: {
      'Grand-Vitara': u,
      'Grand-Vitara-ir': u,
      Jimny: u,
      'Jimny-normal': u,
      Ciaz: s,
      BALENO: h,
      'Fronx GLX': x,
      Kizashi: s,
      Swift: h,
      Celerio: null,
      Dzire: null,
      'S-PRESSO': null,
    },
  },
  Tara: {
    nameFa: 'تارا',
    models: { Manual: s, 'V1 plus': s, v4: s, Automatic: s, V3: null, 'tara EV': null },
  },
  Tiba: { nameFa: 'تیبا', models: { Hatchback: h, Sedan: s } },
  Tigard: {
    nameFa: null,
    models: { 'Tissan S05 1.5L Turbo': x, 'X35-normal': x, 'X35 PRIME': x, 'L7 PLUS': x },
  },
  Toyota: {
    nameFa: 'تویوتا',
    models: {
      Camry: s,
      Corolla: s,
      'Landcruiser 4door': u,
      'Frontlander Hybrid': x,
      'Rav4-normal': x,
      'Prado 4door': u,
      'Levin-Hybrid 1800CC-normal': s,
      'Wildlander Luxury Plus': x,
      'Rav4 2.0L Fwd': x,
      'Prado 2door': u,
      'Hilux double cabin': p,
      'Rav4 Hybrid Awd': x,
      'Rav4 2.0L Awd': x,
      'Yaris Sedan': s,
      BZ3: s,
      'Levin-Hybrid 1800CC Sport Edition': s,
      'Levin-Turbo 1200CC': s,
      Aurion: s,
      'Highlander Hybrid': u,
      'C-HR': x,
      Prius: h,
      'Rav4 Adventure Plus': x,
      'Venza-normal': x,
      Van: v,
      'Wildlander 2.0L Fwd': x,
      'bZ4x-normal': x,
      BZ3X: x,
      'Yaris Hatchback': h,
      'Venza 2.0L luxury plus': x,
      'FJ Cruiser': u,
      'Venza 2.0L premium': x,
      Cressida: s,
      'bZ4x TURBO': x,
      'Hilux single cabin': p,
      Corona: s,
      GT86: c,
      'Landcruiser 2door': u,
      Pickup: p,
      'Rav4 Hybrid-normal': x,
      'Rav4 2.5L Fwd': x,
      Solara: c,
      Carina: s,
      'Avalon Hybrid 2.5L': s,
      Crown: s,
      '4runner': u,
      Furtuner: u,
      Celica: c,
      Echo: null,
      Supra: null,
    },
  },
  Venucia: {
    nameFa: 'ونوسیا',
    models: {
      'V-Online DD-i': x,
      Star: x,
      'Big V': x,
      'V-Online 1.5L Turbo': x,
      'D 60 Plus': null,
      'D60EV Plus': null,
    },
  },
  Volkswagen: {
    nameFa: 'فولکس واگن',
    models: {
      'ID Unyx Pure': x,
      'ID4-normal': x,
      Gol: h,
      'ID Unyx-normal': x,
      'T-ROC': x,
      'Tiguan-normal': x,
      'Tiguan L Pro': x,
      'Tayron L': x,
      'ID4 Pure Plus': x,
      'jetta VS7': x,
      'ID4 Pro': x,
      Golf: h,
      Passat: s,
      Beetle: h,
      Van: v,
      'Jetta VS5': x,
      Caddy: v,
      Atlas: null,
      Pickup: null,
      'jetta-normal': null,
    },
  },
  Volvo: {
    nameFa: 'ولوو',
    models: {
      XC90: u,
      XC70: w,
      EX30: x,
      XC60: x,
      S90: s,
      C30: h,
      C70: k,
      V40: h,
      XC40: null,
    },
  },
  Voyah: { nameFa: 'وویا', models: { 'Free phev': x } },
  XPENG: { nameFa: null, models: { 'MONA M03': s, G6: x, G9: u, 'G9 AWD': u } },
  XTRIM: {
    nameFa: 'اکستریم',
    models: { 'Xtrim (EXEED) LX': x, 'Xtrim (EXEED) VX': u, 'Xtrim (EXEED) TXL': x },
  },
  Zamyad: {
    nameFa: 'زامیاد',
    models: {
      'Z 24': p,
      'Padra Plus': p,
      EX: p,
      Karoon: p,
      'Padra-normal': p,
      Shooka: p,
      Z28: p,
      Zagros: p,
      'Z 28': p,
      Dorka: null,
    },
  },
  Zotye: { nameFa: 'زوتی', models: { DL5: x, 'Z300-im': s } },
  ZX_AUTO: { nameFa: null, models: { G9: p } },
  Škoda: { nameFa: 'اشکودا', models: { Karoq: x, Superb: s, Octavia: s } },
  // Makes Divar counted as one slice on 2026-09-29 (a page or less): their models are learned from what names them.
  AVENTRA: { nameFa: null, models: {} },
  BISU: { nameFa: null, models: {} },
  Borgward: { nameFa: 'بورگوارد', models: {} },
  Buick: { nameFa: 'بیوک', models: {} },
  Changhe: { nameFa: null, models: {} },
  Chevrolet: { nameFa: 'شورولت', models: {} },
  Chrysler: { nameFa: 'کرایسلر', models: {} },
  Dacia: { nameFa: 'داچیا', models: {} },
  Daihatsu: { nameFa: 'دایهاتسو', models: {} },
  Datsun: { nameFa: 'داتسون', models: {} },
  Deer: { nameFa: null, models: {} },
  Dodge: { nameFa: 'دوج', models: {} },
  Domy: { nameFa: null, models: {} },
  Faw: { nameFa: 'فاو', models: {} },
  Ford: { nameFa: 'فورد', models: {} },
  'GAC Gonow': { nameFa: null, models: {} },
  Gaz: { nameFa: 'گاز', models: {} },
  'Hafei Lobo': { nameFa: null, models: {} },
  Hanteng: { nameFa: null, models: {} },
  Hillman: { nameFa: 'هیلمن', models: {} },
  Hummer: { nameFa: 'هامر', models: {} },
  Hyosow: { nameFa: null, models: {} },
  IM: { nameFa: null, models: {} },
  Isuzu: { nameFa: 'ایسوزو', models: {} },
  Iveco: { nameFa: 'ایویکو', models: {} },
  JMC: { nameFa: null, models: {} },
  Jaguar: { nameFa: 'جگوار', models: {} },
  Jetour: { nameFa: 'جتور', models: {} },
  Joylong: { nameFa: null, models: {} },
  'KG Mobility': { nameFa: null, models: {} },
  LAMACO: { nameFa: null, models: {} },
  Lada: { nameFa: 'لادا', models: {} },
  Lamborghini: { nameFa: 'لامبورگینی', models: {} },
  Landmark: { nameFa: null, models: {} },
  Leapmotor: { nameFa: null, models: {} },
  Lotus: { nameFa: 'لوتوس', models: {} },
  Luna: { nameFa: null, models: {} },
  Luxgen: { nameFa: null, models: {} },
  MINI: { nameFa: 'مینی', models: {} },
  Mars: { nameFa: null, models: {} },
  Maserati: { nameFa: 'مازراتی', models: {} },
  Maxus: { nameFa: null, models: {} },
  NETA: { nameFa: null, models: {} },
  Nammi: { nameFa: null, models: {} },
  Oldsmobile: { nameFa: null, models: {} },
  Oshan: { nameFa: null, models: {} },
  Pontiac: { nameFa: 'پونتیاک', models: {} },
  Qingling: { nameFa: null, models: {} },
  Rich: { nameFa: null, models: {} },
  Rigan: { nameFa: null, models: {} },
  Rollsroyce: { nameFa: 'رولز رویس', models: {} },
  Rover: { nameFa: 'روور', models: {} },
  SKYWELL: { nameFa: null, models: {} },
  SWM: { nameFa: null, models: {} },
  Seat: { nameFa: 'سئات', models: {} },
  Sinad: { nameFa: null, models: {} },
  Sinogold: { nameFa: null, models: {} },
  Smart: { nameFa: 'اسمارت', models: {} },
  Soueast: { nameFa: null, models: {} },
  Subaru: { nameFa: 'سوبارو', models: {} },
  Uaz: { nameFa: null, models: {} },
  VGV: { nameFa: null, models: {} },
  infiniti: { nameFa: 'اینفینیتی', models: {} },
  other: { nameFa: 'سایر', models: {} },
};

/**
 * Body types curated with doubt, for a person to confirm (CS-50's notes list them): a name the author could not place
 * with certainty on the Iranian market of 2026.
 */
export const CURATION_DOUBTS: readonly string[] = [
  'Amg Tooca',
  'Amico Asna',
  'BAIC Sabrina',
  'BAIC Sabrina-ir',
  'BMW 225i',
  'Brilliance C3',
  'Chery Queen',
  'Cheval 6 HEV 1.5L Turbo',
  'Citroen Jian',
  'Envoy HEV',
  'Eres hm5',
  'Farda m4 Suba',
  'Gac Trumpchi',
  'Iran Khodro LUNA GRE EV',
  'IranKhodro Van Ghazal',
  'KMC Eagle',
  'KMC SR3',
  'KMC A5',
  'Maxmotor Kalut',
  'MVM M5 Pro',
  'Narvan Taxi',
  'Narvan Personal',
  'Nissan Roniz',
  'Nissan N6 PHEV',
  'Nissan Seranza',
  'PARS KHODRO NOA',
  'PARS KHODRO P90',
  'Rayen V5',
  'Rayen R3',
  'Reera 1.7L Turbo 6 At',
  'Renault PK',
  'Renault Sepand',
  'Saipa Atlas G',
  'Saipa Karvan Saipa',
  'Saipa 421P',
  'Saipa 441P',
  'Saipa Arya',
  'SsangYong Khan',
  'Tigard Tissan S05 1.5L Turbo',
  'Zamyad EX',
  'Zamyad Karoon',
  'Zotye DL5',
  'ZX_AUTO G9',
];

/**
 * Trims whose body type differs from their model's (CS-50 criterion 4), by the model's key and the words in the trim's
 * key: Peugeot's SD versions of its hatchbacks are sedans, and the Corolla Cross is a crossover.
 */
export const TRIM_BODY_TYPES: readonly {
  readonly model: string;
  readonly trimWord: RegExp;
  readonly bodyType: BodyTypeCode;
}[] = [
  { model: 'Peugeot 206', trimWord: /(^| )SD( |$)/, bodyType: 'sedan' },
  { model: 'Peugeot 207i', trimWord: /(^| )SD( |$)/, bodyType: 'sedan' },
  // Divar files the Corolla Cross, a crossover, as trims of the Corolla («Toyota Corolla Corolla CROSS Hybrid»).
  { model: 'Toyota Corolla', trimWord: /(^| )cross( |$)/i, bodyType: 'crossover' },
];
